# Generated by Django 5.2.14 on 2026-05-14 14:33

import django.db.models.deletion
from django.db import migrations, models


CATALOG = {
    "clients": ["view", "create", "update", "delete"],
    "leads": ["view", "create", "update", "delete"],
    "deals": ["view", "create", "update", "delete"],
    "appointments": ["view", "create", "update", "delete"],
    "conversations": ["view", "create", "update", "manage"],
    "tasks": ["view", "create", "update", "delete"],
    "analytics": ["view"],
    "settings": ["view", "update"],
    "team": ["view", "manage"],
    "billing": ["view", "manage"],
    "integrations": ["view", "manage"],
    "automations": ["view", "create", "update", "delete", "manage"],
}

PRESETS = {
    "owner": {"*": {"manage": "business"}},
    "admin": {"*": {"manage": "business"}},
    "manager": {
        "clients": {"view": "business", "create": "business", "update": "business"},
        "leads": {"view": "business", "create": "business", "update": "business"},
        "deals": {"view": "business", "create": "business", "update": "business"},
        "appointments": {"view": "business", "create": "business", "update": "business"},
        "conversations": {"view": "business", "create": "business", "update": "business", "manage": "business"},
        "tasks": {"view": "business", "create": "business", "update": "business"},
        "analytics": {"view": "business"},
        "settings": {"view": "business"},
    },
    "operator": {
        "clients": {"view": "business", "update": "own"},
        "leads": {"view": "business", "create": "business", "update": "own"},
        "conversations": {"view": "business", "create": "business", "update": "own"},
        "tasks": {"view": "own", "update": "own"},
    },
    "marketer": {
        "clients": {"view": "business"},
        "leads": {"view": "business", "create": "business"},
        "analytics": {"view": "business"},
        "automations": {"view": "business", "create": "business", "update": "business"},
    },
    "accountant": {
        "clients": {"view": "business"},
        "analytics": {"view": "business"},
        "billing": {"view": "business"},
    },
    "support": {
        "clients": {"view": "business"},
        "leads": {"view": "business"},
        "deals": {"view": "business"},
        "appointments": {"view": "business"},
        "conversations": {"view": "business"},
    },
    "staff": {
        "clients": {"view": "business"},
        "leads": {"view": "own", "update": "own"},
        "appointments": {"view": "business", "update": "own"},
        "tasks": {"view": "own", "update": "own"},
    },
}


def seed_default_roles(apps, schema_editor):
    Business = apps.get_model("businesses", "Business")
    BusinessMember = apps.get_model("businesses", "BusinessMember")
    BusinessRole = apps.get_model("businesses", "BusinessRole")
    RolePermission = apps.get_model("businesses", "RolePermission")
    RolePreset = apps.get_model("businesses", "RolePreset")

    for role, permissions in PRESETS.items():
        RolePreset.objects.update_or_create(
            key=role,
            defaults={
                "name": role.replace("_", " ").title(),
                "description": "Default access preset.",
                "permissions_json": permissions,
                "is_active": True,
            },
        )

    for business in Business.objects.all():
        for role, permissions in PRESETS.items():
            business_role, _ = BusinessRole.objects.update_or_create(
                business=business,
                preset_key=role,
                defaults={
                    "name": role.replace("_", " ").title(),
                    "description": "Default access preset.",
                    "permissions_json": permissions,
                    "is_system": True,
                    "is_active": True,
                },
            )
            for resource, actions in permissions.items():
                if resource == "*":
                    for catalog_resource, catalog_actions in CATALOG.items():
                        for action in catalog_actions:
                            RolePermission.objects.update_or_create(
                                business_role=business_role,
                                resource=catalog_resource,
                                action=action,
                                defaults={"scope": "business", "is_allowed": True},
                            )
                    continue
                for action, scope in actions.items():
                    RolePermission.objects.update_or_create(
                        business_role=business_role,
                        resource=resource,
                        action=action,
                        defaults={"scope": scope, "is_allowed": True},
                    )

        for member in BusinessMember.objects.filter(business=business, business_role__isnull=True):
            preset_key = "manager" if member.role == "business_manager" else member.role
            member.business_role = BusinessRole.objects.filter(business=business, preset_key=preset_key).first()
            member.save(update_fields=["business_role"])


class Migration(migrations.Migration):

    dependencies = [
        ('businesses', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RolePreset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('key', models.SlugField(max_length=64, unique=True)),
                ('name', models.CharField(max_length=128)),
                ('description', models.TextField(blank=True)),
                ('permissions_json', models.JSONField(blank=True, default=dict)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.AlterField(
            model_name='businessmember',
            name='role',
            field=models.CharField(choices=[('owner', 'Owner'), ('admin', 'Admin'), ('manager', 'Manager'), ('operator', 'Operator'), ('marketer', 'Marketer'), ('accountant', 'Accountant'), ('support', 'Support'), ('staff', 'Staff')], default='staff', max_length=32),
        ),
        migrations.CreateModel(
            name='BusinessRole',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=128)),
                ('preset_key', models.SlugField(blank=True, max_length=64)),
                ('description', models.TextField(blank=True)),
                ('permissions_json', models.JSONField(blank=True, default=dict)),
                ('is_system', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('business', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='roles', to='businesses.business')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='businessmember',
            name='business_role',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='members', to='businesses.businessrole'),
        ),
        migrations.CreateModel(
            name='RolePermission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('resource', models.CharField(max_length=64)),
                ('action', models.CharField(max_length=64)),
                ('scope', models.CharField(choices=[('none', 'None'), ('own', 'Own'), ('team', 'Team'), ('business', 'Business')], default='business', max_length=32)),
                ('is_allowed', models.BooleanField(default=True)),
                ('business_role', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='permissions', to='businesses.businessrole')),
            ],
            options={
                'ordering': ['resource', 'action'],
            },
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=128)),
                ('description', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('business', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='teams', to='businesses.business')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='TeamMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_lead', models.BooleanField(default=False)),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='team_memberships', to='businesses.businessmember')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='team_members', to='businesses.team')),
            ],
        ),
        migrations.AddConstraint(
            model_name='businessrole',
            constraint=models.UniqueConstraint(fields=('business', 'name'), name='unique_business_role_name'),
        ),
        migrations.AddIndex(
            model_name='rolepermission',
            index=models.Index(fields=['resource', 'action', 'is_allowed'], name='businesses__resourc_0e8e91_idx'),
        ),
        migrations.AddConstraint(
            model_name='rolepermission',
            constraint=models.UniqueConstraint(fields=('business_role', 'resource', 'action'), name='unique_business_role_permission'),
        ),
        migrations.AddConstraint(
            model_name='team',
            constraint=models.UniqueConstraint(fields=('business', 'name'), name='unique_business_team_name'),
        ),
        migrations.AddConstraint(
            model_name='teammember',
            constraint=models.UniqueConstraint(fields=('team', 'member'), name='unique_team_member'),
        ),
        migrations.RunPython(seed_default_roles, migrations.RunPython.noop),
    ]
