# Generated by Codex on 2026-05-24

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("businesses", "0003_business_landing_domain_business_landing_id_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="BusinessInvitation",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("email", models.EmailField(max_length=254)),
                ("phone", models.CharField(blank=True, max_length=32)),
                ("telegram", models.CharField(blank=True, max_length=64)),
                ("full_name", models.CharField(blank=True, max_length=255)),
                (
                    "role",
                    models.CharField(
                        choices=[
                            ("owner", "Owner"),
                            ("admin", "Admin"),
                            ("manager", "Manager"),
                            ("operator", "Operator"),
                            ("marketer", "Marketer"),
                            ("accountant", "Accountant"),
                            ("support", "Support"),
                            ("staff", "Staff"),
                        ],
                        default="staff",
                        max_length=32,
                    ),
                ),
                (
                    "delivery_channel",
                    models.CharField(
                        choices=[("email", "Email"), ("whatsapp", "WhatsApp"), ("telegram", "Telegram"), ("manual", "Manual")],
                        default="manual",
                        max_length=32,
                    ),
                ),
                ("token", models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ("expires_at", models.DateTimeField()),
                ("accepted_at", models.DateTimeField(blank=True, null=True)),
                ("revoked_at", models.DateTimeField(blank=True, null=True)),
                (
                    "business",
                    models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="invitations", to="businesses.business"),
                ),
                (
                    "business_role",
                    models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="invitations", to="businesses.businessrole"),
                ),
                (
                    "invited_by",
                    models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="sent_business_invitations", to=settings.AUTH_USER_MODEL),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.AddIndex(
            model_name="businessinvitation",
            index=models.Index(fields=["business", "email", "accepted_at", "revoked_at"], name="businesses__busines_bf8d1a_idx"),
        ),
        migrations.AddIndex(
            model_name="businessinvitation",
            index=models.Index(fields=["token", "expires_at"], name="businesses__token_1ad18b_idx"),
        ),
    ]
