# Generated by Django 5.2.15 on 2026-07-21 08:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('businesses', '0005_business_operational_settings'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='businessmember',
            name='availability_status',
            field=models.CharField(choices=[('available', 'Available'), ('unavailable', 'Unavailable')], default='available', max_length=24),
        ),
        migrations.AddField(
            model_name='businessmember',
            name='fallback_member',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='fallback_for_members', to='businesses.businessmember'),
        ),
        migrations.AddField(
            model_name='businessmember',
            name='unavailable_until',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddIndex(
            model_name='businessmember',
            index=models.Index(fields=['business', 'is_active', 'availability_status'], name='businesses__busines_5f1e48_idx'),
        ),
    ]
