# Generated by Django 5.2.15 on 2026-07-21 09:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('businesses', '0006_businessmember_availability_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='businessinvitation',
            name='team',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='invitations', to='businesses.team'),
        ),
    ]
