# Generated by Django 5.2.15 on 2026-07-21 09:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


MODULES = ("inbox", "leads", "clients", "appointments", "tasks", "deals", "analytics", "ai", "automations", "integrations")


def backfill_capabilities(apps, schema_editor):
    Business = apps.get_model("businesses", "Business")
    BusinessCapability = apps.get_model("businesses", "BusinessCapability")
    rows = []
    for business in Business.objects.all().iterator():
        for module_key in MODULES:
            rows.append(
                BusinessCapability(
                    business_id=business.id,
                    module_key=module_key,
                    is_enabled=not (business.business_type == "dentistry" and module_key == "deals"),
                )
            )
    BusinessCapability.objects.bulk_create(rows, ignore_conflicts=True)


def clear_capabilities(apps, schema_editor):
    apps.get_model("businesses", "BusinessCapability").objects.all().delete()


class Migration(migrations.Migration):

    dependencies = [
        ('businesses', '0007_businessinvitation_team'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='businessinvitation',
            name='role',
            field=models.CharField(choices=[('owner', 'Owner'), ('admin', 'Admin'), ('manager', 'Manager'), ('operator', 'Operator'), ('marketer', 'Marketer'), ('accountant', 'Accountant'), ('support', 'Support'), ('staff', 'Staff'), ('doctor', 'Doctor')], default='staff', max_length=32),
        ),
        migrations.AlterField(
            model_name='businessmember',
            name='role',
            field=models.CharField(choices=[('owner', 'Owner'), ('admin', 'Admin'), ('manager', 'Manager'), ('operator', 'Operator'), ('marketer', 'Marketer'), ('accountant', 'Accountant'), ('support', 'Support'), ('staff', 'Staff'), ('doctor', 'Doctor')], default='staff', max_length=32),
        ),
        migrations.CreateModel(
            name='BusinessCapability',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('module_key', models.CharField(max_length=32)),
                ('is_enabled', models.BooleanField(default=True)),
                ('business', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='capabilities', to='businesses.business')),
                ('configured_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='configured_business_capabilities', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['module_key'],
                'indexes': [models.Index(fields=['business', 'module_key', 'is_enabled'], name='businesses__busines_cea56a_idx')],
                'constraints': [models.UniqueConstraint(fields=('business', 'module_key'), name='unique_business_capability')],
            },
        ),
        migrations.RunPython(backfill_capabilities, clear_capabilities),
    ]
