# Generated by Django 5.2.15 on 2026-07-23 10:08

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('businesses', '0008_alter_businessinvitation_role_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='RoutingPolicy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('resource', models.CharField(choices=[('leads', 'Leads'), ('conversations', 'Conversations'), ('tasks', 'Tasks')], max_length=32)),
                ('mode', models.CharField(choices=[('manual', 'Manual'), ('round_robin', 'Round robin'), ('least_loaded', 'Least loaded')], default='manual', max_length=32)),
                ('unavailable_strategy', models.CharField(choices=[('keep_assigned', 'Keep assigned'), ('member_fallback', 'Use member fallback')], default='keep_assigned', max_length=32)),
                ('eligible_roles', models.JSONField(blank=True, default=list)),
                ('sla_minutes', models.PositiveIntegerField(default=30)),
                ('is_active', models.BooleanField(default=True)),
                ('business', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='routing_policies', to='businesses.business')),
                ('last_assigned_member', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='last_used_by_routing_policies', to='businesses.businessmember')),
                ('team', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='routing_policies', to='businesses.team')),
            ],
            options={
                'ordering': ['business_id', 'resource', 'team_id'],
            },
        ),
        migrations.CreateModel(
            name='SLAAttention',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('resource', models.CharField(choices=[('leads', 'Leads'), ('conversations', 'Conversations'), ('tasks', 'Tasks')], max_length=32)),
                ('entity_id', models.CharField(max_length=64)),
                ('reason', models.CharField(choices=[('unassigned_sla', 'Unassigned SLA'), ('stale_sla', 'Stale SLA')], max_length=32)),
                ('is_active', models.BooleanField(default=True)),
                ('first_detected_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('last_detected_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('notified_at', models.DateTimeField(blank=True, null=True)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('business', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sla_attention_items', to='businesses.business')),
                ('policy', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sla_attention_items', to='businesses.routingpolicy')),
            ],
            options={
                'ordering': ['-last_detected_at'],
            },
        ),
        migrations.AddIndex(
            model_name='routingpolicy',
            index=models.Index(fields=['business', 'resource', 'is_active'], name='businesses__busines_82d345_idx'),
        ),
        migrations.AddConstraint(
            model_name='routingpolicy',
            constraint=models.UniqueConstraint(condition=models.Q(('team__isnull', True)), fields=('business', 'resource'), name='unique_default_routing_policy'),
        ),
        migrations.AddConstraint(
            model_name='routingpolicy',
            constraint=models.UniqueConstraint(condition=models.Q(('team__isnull', False)), fields=('business', 'resource', 'team'), name='unique_team_routing_policy'),
        ),
        migrations.AddIndex(
            model_name='slaattention',
            index=models.Index(fields=['business', 'is_active', 'last_detected_at'], name='businesses__busines_3a5102_idx'),
        ),
        migrations.AddIndex(
            model_name='slaattention',
            index=models.Index(fields=['resource', 'is_active', 'last_detected_at'], name='businesses__resourc_5f1651_idx'),
        ),
        migrations.AddConstraint(
            model_name='slaattention',
            constraint=models.UniqueConstraint(fields=('business', 'resource', 'entity_id', 'reason'), name='unique_sla_attention_incident'),
        ),
    ]
