# Generated by Django 5.2.15 on 2026-08-02 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("businesses", "0009_routingpolicy_slaattention_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="businessinvitation",
            name="role",
            field=models.CharField(
                choices=[
                    ("owner", "Owner"),
                    ("admin", "Admin"),
                    ("manager", "Manager"),
                    ("operator", "Operator"),
                    ("specialist", "Specialist"),
                    ("marketer", "Marketer"),
                    ("accountant", "Accountant"),
                    ("support", "Support"),
                    ("staff", "Staff"),
                    ("doctor", "Doctor"),
                ],
                default="specialist",
                max_length=32,
            ),
        ),
        migrations.AlterField(
            model_name="businessmember",
            name="role",
            field=models.CharField(
                choices=[
                    ("owner", "Owner"),
                    ("admin", "Admin"),
                    ("manager", "Manager"),
                    ("operator", "Operator"),
                    ("specialist", "Specialist"),
                    ("marketer", "Marketer"),
                    ("accountant", "Accountant"),
                    ("support", "Support"),
                    ("staff", "Staff"),
                    ("doctor", "Doctor"),
                ],
                default="specialist",
                max_length=32,
            ),
        ),
    ]
