# Generated by Django 5.2.14 on 2026-05-27 17:19

import django.db.models.deletion
import django.utils.timezone
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('businesses', '0004_businessinvitation'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='KaspiPricingRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_sku', models.CharField(max_length=160)),
                ('product_name', models.CharField(blank=True, max_length=255)),
                ('kaspi_product_id', models.CharField(blank=True, max_length=160)),
                ('current_price', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=14)),
                ('min_price', models.DecimalField(decimal_places=2, max_digits=14)),
                ('step_amount', models.DecimalField(decimal_places=2, default=Decimal('1.00'), max_digits=10)),
                ('mode', models.CharField(choices=[('recommend', 'Recommend'), ('approval', 'Approval'), ('autopilot', 'Autopilot')], default='recommend', max_length=32)),
                ('status', models.CharField(choices=[('active', 'Active'), ('paused', 'Paused'), ('archived', 'Archived')], default='active', max_length=32)),
                ('max_changes_per_day', models.PositiveIntegerField(default=3)),
                ('config_json', models.JSONField(blank=True, default=dict)),
                ('last_checked_at', models.DateTimeField(blank=True, null=True)),
                ('last_recommended_price', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True)),
                ('last_applied_price', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True)),
                ('last_error', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('business', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='kaspi_pricing_rules', to='businesses.business')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_kaspi_pricing_rules', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['product_sku', 'id'],
            },
        ),
        migrations.CreateModel(
            name='KaspiPricingRecommendation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('current_price', models.DecimalField(decimal_places=2, max_digits=14)),
                ('competitor_price', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True)),
                ('target_price', models.DecimalField(decimal_places=2, max_digits=14)),
                ('min_price', models.DecimalField(decimal_places=2, max_digits=14)),
                ('delta', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=14)),
                ('reason', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('proposed', 'Proposed'), ('blocked', 'Blocked'), ('approved', 'Approved'), ('applied', 'Applied'), ('skipped', 'Skipped'), ('failed', 'Failed')], default='proposed', max_length=32)),
                ('decision_json', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('business', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='kaspi_pricing_recommendations', to='businesses.business')),
                ('rule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recommendations', to='pricing.kaspipricingrule')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='KaspiPriceChangeLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('old_price', models.DecimalField(decimal_places=2, max_digits=14)),
                ('new_price', models.DecimalField(decimal_places=2, max_digits=14)),
                ('status', models.CharField(choices=[('simulated', 'Simulated'), ('queued', 'Queued'), ('applied', 'Applied'), ('blocked', 'Blocked'), ('failed', 'Failed')], default='simulated', max_length=32)),
                ('mode', models.CharField(blank=True, max_length=32)),
                ('provider_response_json', models.JSONField(blank=True, default=dict)),
                ('error', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('business', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='kaspi_price_change_logs', to='businesses.business')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='kaspi_price_changes', to=settings.AUTH_USER_MODEL)),
                ('recommendation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='change_logs', to='pricing.kaspipricingrecommendation')),
                ('rule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='price_change_logs', to='pricing.kaspipricingrule')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='KaspiCompetitorOffer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('competitor_name', models.CharField(max_length=255)),
                ('competitor_merchant_id', models.CharField(blank=True, max_length=160)),
                ('price', models.DecimalField(decimal_places=2, max_digits=14)),
                ('position', models.PositiveIntegerField(default=0)),
                ('available', models.BooleanField(default=True)),
                ('payload_json', models.JSONField(blank=True, default=dict)),
                ('observed_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('business', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='kaspi_competitor_offers', to='businesses.business')),
                ('rule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='competitor_offers', to='pricing.kaspipricingrule')),
            ],
            options={
                'ordering': ['price', 'position', 'id'],
            },
        ),
        migrations.AddIndex(
            model_name='kaspipricingrule',
            index=models.Index(fields=['business', 'status', 'mode'], name='pricing_kas_busines_c0c812_idx'),
        ),
        migrations.AddIndex(
            model_name='kaspipricingrule',
            index=models.Index(fields=['business', 'product_sku'], name='pricing_kas_busines_3e76ee_idx'),
        ),
        migrations.AddConstraint(
            model_name='kaspipricingrule',
            constraint=models.UniqueConstraint(fields=('business', 'product_sku'), name='unique_business_kaspi_pricing_sku'),
        ),
        migrations.AddIndex(
            model_name='kaspipricingrecommendation',
            index=models.Index(fields=['business', 'status', 'created_at'], name='pricing_kas_busines_0e6289_idx'),
        ),
        migrations.AddIndex(
            model_name='kaspipricingrecommendation',
            index=models.Index(fields=['rule', 'status'], name='pricing_kas_rule_id_638669_idx'),
        ),
        migrations.AddIndex(
            model_name='kaspipricechangelog',
            index=models.Index(fields=['business', 'status', 'created_at'], name='pricing_kas_busines_90ff82_idx'),
        ),
        migrations.AddIndex(
            model_name='kaspipricechangelog',
            index=models.Index(fields=['rule', 'created_at'], name='pricing_kas_rule_id_96ceda_idx'),
        ),
        migrations.AddIndex(
            model_name='kaspicompetitoroffer',
            index=models.Index(fields=['business', 'rule', 'observed_at'], name='pricing_kas_busines_21257c_idx'),
        ),
        migrations.AddIndex(
            model_name='kaspicompetitoroffer',
            index=models.Index(fields=['rule', 'price'], name='pricing_kas_rule_id_5319f8_idx'),
        ),
    ]
