# Generated by Django 5.2.14 on 2026-05-27 18:00

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('businesses', '0004_businessinvitation'),
        ('pricing', '0002_kaspipricingrule_autopilot_confirmed_at_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PricingCatalogItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source', models.CharField(max_length=64)),
                ('external_id', models.CharField(blank=True, max_length=160)),
                ('sku', models.CharField(max_length=160)),
                ('name', models.CharField(blank=True, max_length=255)),
                ('current_price', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True)),
                ('stock_quantity', models.DecimalField(blank=True, decimal_places=3, max_digits=14, null=True)),
                ('payload_json', models.JSONField(blank=True, default=dict)),
                ('last_seen_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('business', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pricing_catalog_items', to='businesses.business')),
            ],
            options={
                'ordering': ['source', 'sku', 'id'],
                'indexes': [models.Index(fields=['business', 'source', 'sku'], name='pricing_pri_busines_4746c8_idx'), models.Index(fields=['business', 'last_seen_at'], name='pricing_pri_busines_d02540_idx')],
                'constraints': [models.UniqueConstraint(fields=('business', 'source', 'sku'), name='unique_business_pricing_catalog_source_sku')],
            },
        ),
    ]
