# Generated by Django 5.2.14 on 2026-05-27 18:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('businesses', '0004_businessinvitation'),
        ('pricing', '0003_pricingcatalogitem'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='KaspiPricingControl',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('emergency_stop_enabled', models.BooleanField(default=False)),
                ('emergency_stop_reason', models.TextField(blank=True)),
                ('stopped_at', models.DateTimeField(blank=True, null=True)),
                ('resumed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('business', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='kaspi_pricing_control', to='businesses.business')),
                ('resumed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='resumed_kaspi_pricing_controls', to=settings.AUTH_USER_MODEL)),
                ('stopped_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='stopped_kaspi_pricing_controls', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['business_id'],
            },
        ),
        migrations.CreateModel(
            name='KaspiPricingAlert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alert_type', models.CharField(choices=[('emergency_stop', 'Emergency stop'), ('write_failed', 'Write failed'), ('change_blocked', 'Change blocked'), ('monitor_failed', 'Monitor failed'), ('frequent_changes', 'Frequent changes')], max_length=64)),
                ('severity', models.CharField(choices=[('info', 'Info'), ('warning', 'Warning'), ('critical', 'Critical')], default='warning', max_length=32)),
                ('status', models.CharField(choices=[('open', 'Open'), ('resolved', 'Resolved')], default='open', max_length=32)),
                ('title', models.CharField(max_length=255)),
                ('message', models.TextField(blank=True)),
                ('payload_json', models.JSONField(blank=True, default=dict)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('business', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='kaspi_pricing_alerts', to='businesses.business')),
                ('change_log', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='alerts', to='pricing.kaspipricechangelog')),
                ('rule', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='alerts', to='pricing.kaspipricingrule')),
            ],
            options={
                'ordering': ['status', '-created_at'],
                'indexes': [models.Index(fields=['business', 'status', 'severity'], name='pricing_kas_busines_f9a9c2_idx'), models.Index(fields=['business', 'alert_type', 'created_at'], name='pricing_kas_busines_a46051_idx')],
            },
        ),
    ]
