# Generated by Django 5.2.14 on 2026-05-13 08:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('businesses', '0001_initial'),
        ('clients', '0001_initial'),
        ('crm', '0002_default_pipeline'),
        ('leads', '0001_initial'),
        ('scheduling', '0001_initial'),
        ('tasks', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='appointment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tasks', to='scheduling.appointment'),
        ),
        migrations.AddIndex(
            model_name='task',
            index=models.Index(fields=['appointment', 'status'], name='tasks_task_appoint_da66d2_idx'),
        ),
    ]
