# Generated by Django 5.2.15 on 2026-06-20 12:31

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('businesses', '0005_business_operational_settings'),
        ('clients', '0003_clientmergelog'),
        ('crm', '0006_remove_deal_crm_deal_busi_client_arch_idx'),
        ('leads', '0007_remove_lead_lead_lead_busi_client_arch_idx_and_more'),
        ('scheduling', '0005_remove_appointment_sched_appoint_busi_client_arch_idx'),
        ('tasks', '0007_task_cancel_reason_task_cancelled_at_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='task',
            index=models.Index(fields=['business', 'assignee', 'due_at'], name='tasks_task_busines_38b472_idx'),
        ),
        migrations.AddIndex(
            model_name='task',
            index=models.Index(fields=['business', 'priority', 'due_at'], name='tasks_task_busines_e95b8a_idx'),
        ),
        migrations.AddIndex(
            model_name='task',
            index=models.Index(fields=['business', 'due_at', 'updated_at'], name='tasks_task_busines_7aeade_idx'),
        ),
        migrations.AddIndex(
            model_name='task',
            index=models.Index(fields=['business', 'updated_at'], name='tasks_task_busines_31249b_idx'),
        ),
    ]
