# Generated by Django 5.2.15 on 2026-07-09 16:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bots', '0007_remove_botconversation_bots_botconv_busi_client_arch_idx'),
        ('businesses', '0005_business_operational_settings'),
        ('clients', '0005_client_source_attribution'),
        ('crm', '0008_dealvaluehistory'),
        ('leads', '0007_remove_lead_lead_lead_busi_client_arch_idx_and_more'),
        ('scheduling', '0005_remove_appointment_sched_appoint_busi_client_arch_idx'),
        ('tasks', '0008_task_tasks_task_busines_38b472_idx_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='conversation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tasks', to='bots.botconversation'),
        ),
        migrations.AddIndex(
            model_name='task',
            index=models.Index(fields=['conversation', 'status'], name='tasks_task_convers_176087_idx'),
        ),
    ]
