# Generated by Codex on 2026-05-12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="role",
            field=models.CharField(
                choices=[
                    ("platform_admin", "Platform admin"),
                    ("platform_manager", "Platform manager"),
                    ("business_owner", "Business owner"),
                    ("business_manager", "Business manager"),
                    ("manager", "Manager"),
                    ("staff", "Staff"),
                ],
                default="business_owner",
                max_length=32,
            ),
        ),
    ]
