# Generated by Django 5.2.14 on 2026-05-19 19:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_update_user_roles'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('platform_admin', 'Platform admin'), ('platform_manager', 'Platform manager'), ('business_owner', 'Business owner'), ('business_manager', 'Business manager'), ('business_operator', 'Business operator'), ('manager', 'Manager'), ('staff', 'Staff')], default='business_owner', max_length=32),
        ),
    ]
