# Generated by Codex on 2026-05-24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0003_alter_user_role"),
    ]

    operations = [
        migrations.CreateModel(
            name="SocialIdentity",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("provider", models.CharField(choices=[("google", "Google"), ("apple", "Apple")], max_length=32)),
                ("subject", models.CharField(max_length=255)),
                ("email", models.EmailField(max_length=254)),
                ("email_verified", models.BooleanField(default=False)),
                ("raw_claims", models.JSONField(blank=True, default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="social_identities", to=settings.AUTH_USER_MODEL),
                ),
            ],
        ),
        migrations.AddConstraint(
            model_name="socialidentity",
            constraint=models.UniqueConstraint(fields=("provider", "subject"), name="accounts_social_identity_provider_subject_uniq"),
        ),
        migrations.AddIndex(
            model_name="socialidentity",
            index=models.Index(fields=["provider", "email"], name="acct_social_provider_email_idx"),
        ),
        migrations.AddIndex(
            model_name="socialidentity",
            index=models.Index(fields=["user", "provider"], name="acct_social_user_provider_idx"),
        ),
    ]
