# Generated by Codex on 2026-06-03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0004_socialidentity"),
    ]

    operations = [
        migrations.CreateModel(
            name="UserPreference",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("language", models.CharField(choices=[("ru", "Russian"), ("kk", "Kazakh"), ("en", "English")], default="ru", max_length=8)),
                ("timezone", models.CharField(default="Asia/Almaty", max_length=64)),
                ("start_page", models.CharField(choices=[("dashboard", "Dashboard"), ("conversations", "Conversations"), ("tasks", "Tasks"), ("calendar", "Calendar"), ("leads", "Leads")], default="dashboard", max_length=32)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("user", models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name="preferences", to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
