# Generated by Django 5.2.17 on 2026-08-21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0006_privileged_mfa"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="auth_epoch",
            field=models.PositiveBigIntegerField(default=0),
        ),
    ]
