# Generated by Codex on 2026-05-12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("businesses", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="SubscriptionPlan",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=128)),
                ("code", models.SlugField(max_length=64, unique=True)),
                ("monthly_price", models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ("description", models.TextField(blank=True)),
                ("is_active", models.BooleanField(default=True)),
                ("limits_json", models.JSONField(blank=True, default=dict)),
                ("features_json", models.JSONField(blank=True, default=dict)),
            ],
            options={
                "ordering": ["monthly_price", "name"],
            },
        ),
        migrations.CreateModel(
            name="Subscription",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("status", models.CharField(choices=[("trial", "Trial"), ("active", "Active"), ("overdue", "Overdue"), ("cancelled", "Cancelled"), ("paused", "Paused")], default="trial", max_length=32)),
                ("started_at", models.DateTimeField(blank=True, null=True)),
                ("next_payment_at", models.DateTimeField(blank=True, null=True)),
                ("cancelled_at", models.DateTimeField(blank=True, null=True)),
                ("business", models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name="subscription", to="businesses.business")),
                ("plan", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name="subscriptions", to="billing.subscriptionplan")),
            ],
            options={
                "ordering": ["business__name"],
            },
        ),
    ]
