# Generated by Codex on 2026-05-12

from django.db import migrations


PLANS = [
    {
        "name": "Start",
        "code": "start",
        "monthly_price": "0.00",
        "description": "Для тестов, демо и первых клиентов.",
        "limits_json": {"businesses": 1, "users": 3, "ai_requests": 0},
        "features_json": {"features": ["CRM foundation", "Clients and leads", "Calendar MVP"]},
    },
    {
        "name": "Growth",
        "code": "growth",
        "monthly_price": "29900.00",
        "description": "Для малого бизнеса, которому нужны CRM, боты и автоматизации.",
        "limits_json": {"businesses": 1, "users": 10, "ai_requests": 1000},
        "features_json": {"features": ["CRM workspace", "AI bots foundation", "Automation rules"]},
    },
    {
        "name": "Platform",
        "code": "platform",
        "monthly_price": "99000.00",
        "description": "Для сетей, агентств и platform scenarios.",
        "limits_json": {"businesses": 10, "users": 50, "ai_requests": 10000},
        "features_json": {"features": ["Platform admin", "Support access", "Advanced analytics"]},
    },
]


def seed_plans(apps, schema_editor):
    SubscriptionPlan = apps.get_model("billing", "SubscriptionPlan")
    for plan in PLANS:
        SubscriptionPlan.objects.update_or_create(
            code=plan["code"],
            defaults={
                **plan,
                "is_active": True,
            },
        )


def remove_seeded_plans(apps, schema_editor):
    SubscriptionPlan = apps.get_model("billing", "SubscriptionPlan")
    SubscriptionPlan.objects.filter(code__in=[plan["code"] for plan in PLANS]).delete()


class Migration(migrations.Migration):

    dependencies = [
        ("billing", "0001_initial"),
    ]

    operations = [
        migrations.RunPython(seed_plans, remove_seeded_plans),
    ]
