# Generated by Django 5.2.14 on 2026-05-13 12:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0002_seed_plans'),
        ('businesses', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UsageCounter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('period_start', models.DateField()),
                ('period_end', models.DateField()),
                ('metric', models.CharField(choices=[('ai_requests', 'AI requests'), ('bot_messages', 'Bot messages'), ('users', 'Users'), ('conversations', 'Conversations')], max_length=32)),
                ('value', models.PositiveIntegerField(default=0)),
                ('business', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='usage_counters', to='businesses.business')),
            ],
            options={
                'indexes': [models.Index(fields=['business', 'metric', 'period_start'], name='billing_usa_busines_649e4e_idx')],
                'constraints': [models.UniqueConstraint(fields=('business', 'period_start', 'period_end', 'metric'), name='unique_usage_counter_period_metric')],
            },
        ),
    ]
