# Generated by Django 5.2.14 on 2026-05-20 09:28

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('businesses', '0002_rolepreset_alter_businessmember_role_businessrole_and_more'),
        ('integrations', '0002_webhookendpoint_webhookdeliverylog_apitoken_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BusinessConnector',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provider', models.CharField(choices=[('website', 'Website'), ('telegram', 'Telegram'), ('whatsapp', 'WhatsApp'), ('instagram', 'Instagram'), ('email', 'Email'), ('kaspi', 'Kaspi'), ('1c', '1C'), ('google_calendar', 'Google Calendar'), ('custom', 'Custom')], max_length=64)),
                ('capability', models.CharField(choices=[('communications', 'Communications'), ('sales', 'Sales'), ('calendar', 'Calendar'), ('finance', 'Finance'), ('inventory', 'Inventory'), ('marketing', 'Marketing'), ('custom', 'Custom')], default='communications', max_length=64)),
                ('name', models.CharField(max_length=128)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('connected', 'Connected'), ('needs_attention', 'Needs attention'), ('syncing', 'Syncing'), ('failed', 'Failed'), ('disabled', 'Disabled'), ('expired_credentials', 'Expired credentials')], default='draft', max_length=32)),
                ('auth_type', models.CharField(choices=[('none', 'None'), ('token', 'Token'), ('oauth', 'OAuth'), ('qr', 'QR'), ('login', 'Login'), ('connector', 'Connector')], default='none', max_length=32)),
                ('config_json', models.JSONField(blank=True, default=dict)),
                ('scopes_json', models.JSONField(blank=True, default=list)),
                ('last_sync_at', models.DateTimeField(blank=True, null=True)),
                ('next_sync_at', models.DateTimeField(blank=True, null=True)),
                ('last_error', models.TextField(blank=True)),
                ('connected_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('business', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='business_connectors', to='businesses.business')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_business_connectors', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['provider', 'name'],
            },
        ),
        migrations.CreateModel(
            name='BusinessEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(max_length=128)),
                ('source', models.CharField(max_length=64)),
                ('external_id', models.CharField(blank=True, max_length=160)),
                ('deduplication_key', models.CharField(max_length=160)),
                ('occurred_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('processed_at', models.DateTimeField(blank=True, null=True)),
                ('payload_json', models.JSONField(blank=True, default=dict)),
                ('status', models.CharField(choices=[('received', 'Received'), ('processed', 'Processed'), ('failed', 'Failed'), ('ignored', 'Ignored')], default='received', max_length=32)),
                ('error', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('business', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='business_events', to='businesses.business')),
                ('connector', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='events', to='integrations.businessconnector')),
            ],
            options={
                'ordering': ['-occurred_at', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ConnectorCredential',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=96)),
                ('encrypted_value', models.TextField()),
                ('masked_value', models.CharField(blank=True, max_length=160)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('rotated_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('business', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='connector_credentials', to='businesses.business')),
                ('connector', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='credentials', to='integrations.businessconnector')),
            ],
            options={
                'ordering': ['key'],
            },
        ),
        migrations.CreateModel(
            name='ConnectorSyncRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mode', models.CharField(choices=[('webhook', 'Webhook'), ('pull', 'Pull'), ('manual', 'Manual'), ('healthcheck', 'Healthcheck')], default='manual', max_length=32)),
                ('status', models.CharField(choices=[('queued', 'Queued'), ('running', 'Running'), ('succeeded', 'Succeeded'), ('failed', 'Failed')], default='queued', max_length=32)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('events_received', models.PositiveIntegerField(default=0)),
                ('events_processed', models.PositiveIntegerField(default=0)),
                ('error', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('business', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='connector_sync_runs', to='businesses.business')),
                ('connector', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sync_runs', to='integrations.businessconnector')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='businessconnector',
            index=models.Index(fields=['business', 'provider', 'status'], name='integration_busines_ca9180_idx'),
        ),
        migrations.AddIndex(
            model_name='businessconnector',
            index=models.Index(fields=['business', 'capability', 'status'], name='integration_busines_ff98da_idx'),
        ),
        migrations.AddConstraint(
            model_name='businessconnector',
            constraint=models.UniqueConstraint(fields=('business', 'provider', 'name'), name='unique_business_connector_name'),
        ),
        migrations.AddIndex(
            model_name='businessevent',
            index=models.Index(fields=['business', 'source', 'event_type', 'occurred_at'], name='integration_busines_89319e_idx'),
        ),
        migrations.AddIndex(
            model_name='businessevent',
            index=models.Index(fields=['business', 'status', 'created_at'], name='integration_busines_58e4f6_idx'),
        ),
        migrations.AddConstraint(
            model_name='businessevent',
            constraint=models.UniqueConstraint(fields=('business', 'source', 'deduplication_key'), name='unique_business_event_deduplication_key'),
        ),
        migrations.AddIndex(
            model_name='connectorcredential',
            index=models.Index(fields=['business', 'connector', 'key'], name='integration_busines_c4201b_idx'),
        ),
        migrations.AddIndex(
            model_name='connectorcredential',
            index=models.Index(fields=['expires_at'], name='integration_expires_8e820d_idx'),
        ),
        migrations.AddConstraint(
            model_name='connectorcredential',
            constraint=models.UniqueConstraint(fields=('connector', 'key'), name='unique_connector_credential_key'),
        ),
        migrations.AddIndex(
            model_name='connectorsyncrun',
            index=models.Index(fields=['business', 'connector', 'status', 'created_at'], name='integration_busines_8cfcb0_idx'),
        ),
        migrations.AddIndex(
            model_name='connectorsyncrun',
            index=models.Index(fields=['mode', 'status', 'created_at'], name='integration_mode_070176_idx'),
        ),
    ]
