# Generated by Django 5.2.14 on 2026-05-22 19:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('integrations', '0003_businessconnector_businessevent_connectorcredential_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='businessconnector',
            name='provider',
            field=models.CharField(choices=[('website', 'Website'), ('telegram', 'Telegram'), ('whatsapp', 'WhatsApp'), ('instagram', 'Instagram'), ('email', 'Email'), ('kaspi', 'Kaspi'), ('1c', '1C'), ('google_calendar', 'Google Calendar'), ('excel_csv', 'Excel / CSV'), ('google_sheets', 'Google Sheets'), ('moysklad', 'МойСклад'), ('wildberries', 'Wildberries'), ('ozon', 'Ozon'), ('yandex_market', 'Яндекс.Маркет'), ('custom', 'Custom')], max_length=64),
        ),
    ]
