# Generated by Django 5.2.14 on 2026-05-24 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('integrations', '0004_add_pilot_connector_providers'),
    ]

    operations = [
        migrations.AlterField(
            model_name='businessconnector',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('connected', 'Connected'), ('pending_request', 'Pending request'), ('setup_required', 'Setup required'), ('provider_configuring', 'Provider configuring'), ('error', 'Error'), ('disconnected', 'Disconnected'), ('needs_attention', 'Needs attention'), ('syncing', 'Syncing'), ('failed', 'Failed'), ('disabled', 'Disabled'), ('expired_credentials', 'Expired credentials')], default='draft', max_length=32),
        ),
    ]
