# Generated by Django 5.2.14 on 2026-05-13 11:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai_core', '0001_initial'),
        ('bots', '0003_botconversation_assigned_to_and_more'),
        ('businesses', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AgentProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255)),
                ('role_description', models.TextField(blank=True)),
                ('tone', models.CharField(choices=[('friendly', 'Friendly'), ('expert', 'Expert'), ('formal', 'Formal'), ('sales', 'Sales'), ('support', 'Support')], default='friendly', max_length=32)),
                ('language', models.CharField(default='ru', max_length=16)),
                ('is_active', models.BooleanField(default=True)),
                ('system_prompt', models.TextField(blank=True)),
                ('rules_json', models.JSONField(blank=True, default=dict)),
                ('allowed_tools_json', models.JSONField(blank=True, default=dict)),
                ('escalation_rules_json', models.JSONField(blank=True, default=dict)),
                ('bot', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='agent_profiles', to='bots.bot')),
                ('business', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='agent_profiles', to='businesses.business')),
            ],
            options={
                'ordering': ['-is_active', 'name'],
                'indexes': [models.Index(fields=['business', 'is_active'], name='ai_core_age_busines_f6a618_idx'), models.Index(fields=['bot', 'is_active'], name='ai_core_age_bot_id_1ed542_idx')],
            },
        ),
    ]
