# Generated by Django 5.2.14 on 2026-06-01 12:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai_core', '0003_aitoolcalllog'),
        ('businesses', '0004_businessinvitation'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ApprovalRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('required_role', models.CharField(blank=True, max_length=32)),
                ('action_type', models.CharField(choices=[('ai_pipeline', 'AI pipeline'), ('ai_outreach', 'AI outreach'), ('ai_automation', 'AI automation'), ('campaign_launch', 'Campaign launch'), ('appointment_change', 'Appointment change'), ('export', 'Export')], max_length=64)),
                ('payload', models.JSONField(blank=True, default=dict)),
                ('source_object_type', models.CharField(blank=True, max_length=64)),
                ('source_object_id', models.CharField(blank=True, max_length=64)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('expired', 'Expired'), ('executed', 'Executed')], default='pending', max_length=32)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('rejected_at', models.DateTimeField(blank=True, null=True)),
                ('reason', models.TextField(blank=True)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('ai_request_log', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approval_requests', to='ai_core.airequestlog')),
                ('ai_tool_call_log', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approval_requests', to='ai_core.aitoolcalllog')),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_ai_requests', to=settings.AUTH_USER_MODEL)),
                ('business', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='approval_requests', to='businesses.business')),
                ('rejected_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rejected_ai_requests', to=settings.AUTH_USER_MODEL)),
                ('requested_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approval_requests', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['business', 'status', 'action_type'], name='ai_core_app_busines_e16f95_idx'), models.Index(fields=['requested_by', 'status'], name='ai_core_app_request_c0ddb9_idx')],
            },
        ),
    ]
