# Generated by Django 5.2.15 on 2026-07-21 08:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai_core', '0004_approvalrequest'),
        ('businesses', '0005_business_operational_settings'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='aitoolcalllog',
            name='attempts',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='aitoolcalllog',
            name='executed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='aitoolcalllog',
            name='locked_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='aitoolcalllog',
            name='status',
            field=models.CharField(choices=[('suggested', 'Suggested'), ('executing', 'Executing'), ('executed', 'Executed'), ('failed', 'Failed'), ('rejected', 'Rejected')], default='suggested', max_length=32),
        ),
        migrations.CreateModel(
            name='AIJob',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('source', models.CharField(choices=[('crm', 'CRM'), ('bot', 'Bot'), ('automation', 'Automation')], default='crm', max_length=32)),
                ('prompt_type', models.CharField(max_length=64)),
                ('input_json', models.JSONField(blank=True, default=dict)),
                ('result_json', models.JSONField(blank=True, default=dict)),
                ('idempotency_key', models.CharField(max_length=160)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('running', 'Running'), ('retry_scheduled', 'Retry scheduled'), ('succeeded', 'Succeeded'), ('failed', 'Failed')], default='pending', max_length=32)),
                ('attempts', models.PositiveSmallIntegerField(default=0)),
                ('max_attempts', models.PositiveSmallIntegerField(default=3)),
                ('next_retry_at', models.DateTimeField(blank=True, null=True)),
                ('locked_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('error', models.TextField(blank=True)),
                ('business', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ai_jobs', to='businesses.business')),
                ('request_log', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='job', to='ai_core.airequestlog')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ai_jobs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['business', 'status', 'created_at'], name='ai_core_aij_busines_848a49_idx'), models.Index(fields=['status', 'next_retry_at'], name='ai_core_aij_status_f57925_idx')],
                'constraints': [models.UniqueConstraint(fields=('business', 'idempotency_key'), name='unique_ai_job_idempotency_key')],
            },
        ),
    ]
