# Generated by Django 5.2.15 on 2026-06-27 09:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('businesses', '0005_business_operational_settings'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MobileDevice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('device_id_hash', models.CharField(max_length=64)),
                ('platform', models.CharField(choices=[('ios', 'iOS'), ('android', 'Android')], max_length=16)),
                ('app_version', models.CharField(blank=True, max_length=32)),
                ('build_number', models.CharField(blank=True, max_length=32)),
                ('os_version', models.CharField(blank=True, max_length=64)),
                ('device_model', models.CharField(blank=True, max_length=128)),
                ('last_seen_at', models.DateTimeField(blank=True, null=True)),
                ('last_ip', models.GenericIPAddressField(blank=True, null=True)),
                ('revoked_at', models.DateTimeField(blank=True, null=True)),
                ('revoked_reason', models.CharField(blank=True, max_length=255)),
                ('business', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mobile_devices', to='businesses.business')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mobile_devices', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-last_seen_at', '-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='MobileIdempotencyKey',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('endpoint', models.CharField(max_length=255)),
                ('key_hash', models.CharField(max_length=64)),
                ('request_hash', models.CharField(blank=True, max_length=64)),
                ('response_status', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('response_json', models.JSONField(blank=True, default=dict)),
                ('expires_at', models.DateTimeField()),
                ('business', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mobile_idempotency_keys', to='businesses.business')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mobile_idempotency_keys', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='MobilePushToken',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('provider', models.CharField(choices=[('apns', 'APNs'), ('fcm', 'FCM'), ('expo', 'Expo')], max_length=16)),
                ('token_hash', models.CharField(max_length=64)),
                ('is_active', models.BooleanField(default=True)),
                ('last_seen_at', models.DateTimeField(blank=True, null=True)),
                ('revoked_at', models.DateTimeField(blank=True, null=True)),
                ('revoked_reason', models.CharField(blank=True, max_length=255)),
                ('business', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mobile_push_tokens', to='businesses.business')),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='push_tokens', to='mobile.mobiledevice')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mobile_push_tokens', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-last_seen_at', '-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='MobileSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('refresh_jti', models.CharField(db_index=True, max_length=255)),
                ('status', models.CharField(choices=[('active', 'Active'), ('revoked', 'Revoked'), ('expired', 'Expired')], default='active', max_length=16)),
                ('last_seen_at', models.DateTimeField(blank=True, null=True)),
                ('revoked_at', models.DateTimeField(blank=True, null=True)),
                ('revoked_reason', models.CharField(blank=True, max_length=255)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('business', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mobile_sessions', to='businesses.business')),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sessions', to='mobile.mobiledevice')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mobile_sessions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-last_seen_at', '-updated_at'],
            },
        ),
        migrations.AddIndex(
            model_name='mobiledevice',
            index=models.Index(fields=['business', 'user', 'revoked_at'], name='mobile_mobi_busines_6aa268_idx'),
        ),
        migrations.AddIndex(
            model_name='mobiledevice',
            index=models.Index(fields=['business', 'platform', 'last_seen_at'], name='mobile_mobi_busines_5e990b_idx'),
        ),
        migrations.AddIndex(
            model_name='mobiledevice',
            index=models.Index(fields=['device_id_hash'], name='mobile_mobi_device__32e5fa_idx'),
        ),
        migrations.AddConstraint(
            model_name='mobiledevice',
            constraint=models.UniqueConstraint(fields=('business', 'user', 'device_id_hash'), name='unique_mobile_device_per_user_business'),
        ),
        migrations.AddIndex(
            model_name='mobileidempotencykey',
            index=models.Index(fields=['business', 'user', 'expires_at'], name='mobile_mobi_busines_9acad6_idx'),
        ),
        migrations.AddIndex(
            model_name='mobileidempotencykey',
            index=models.Index(fields=['endpoint', 'key_hash'], name='mobile_mobi_endpoin_e2e690_idx'),
        ),
        migrations.AddConstraint(
            model_name='mobileidempotencykey',
            constraint=models.UniqueConstraint(fields=('business', 'user', 'endpoint', 'key_hash'), name='unique_mobile_idempotency_key'),
        ),
        migrations.AddIndex(
            model_name='mobilepushtoken',
            index=models.Index(fields=['business', 'user', 'is_active'], name='mobile_mobi_busines_85d139_idx'),
        ),
        migrations.AddIndex(
            model_name='mobilepushtoken',
            index=models.Index(fields=['business', 'device', 'is_active'], name='mobile_mobi_busines_ca9efa_idx'),
        ),
        migrations.AddIndex(
            model_name='mobilepushtoken',
            index=models.Index(fields=['provider', 'token_hash'], name='mobile_mobi_provide_87c71a_idx'),
        ),
        migrations.AddConstraint(
            model_name='mobilepushtoken',
            constraint=models.UniqueConstraint(fields=('business', 'provider', 'token_hash'), name='unique_mobile_push_token_per_business'),
        ),
        migrations.AddIndex(
            model_name='mobilesession',
            index=models.Index(fields=['business', 'user', 'status'], name='mobile_mobi_busines_ae9cda_idx'),
        ),
        migrations.AddIndex(
            model_name='mobilesession',
            index=models.Index(fields=['business', 'device', 'status'], name='mobile_mobi_busines_4d656c_idx'),
        ),
        migrations.AddIndex(
            model_name='mobilesession',
            index=models.Index(fields=['expires_at', 'status'], name='mobile_mobi_expires_1c5ac5_idx'),
        ),
        migrations.AddConstraint(
            model_name='mobilesession',
            constraint=models.UniqueConstraint(fields=('business', 'user', 'refresh_jti'), name='unique_mobile_session_refresh_jti'),
        ),
    ]
