# Generated by Django 5.2.14 on 2026-05-11 16:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('businesses', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AutomationRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255)),
                ('trigger_type', models.CharField(choices=[('lead_created', 'Lead created'), ('deal_created', 'Deal created'), ('stage_changed', 'Stage changed'), ('message_received', 'Message received'), ('task_overdue', 'Task overdue'), ('appointment_created', 'Appointment created'), ('appointment_cancelled', 'Appointment cancelled'), ('client_inactive', 'Client inactive'), ('tag_added', 'Tag added'), ('tag_removed', 'Tag removed')], max_length=64)),
                ('description', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=False)),
                ('priority', models.PositiveIntegerField(default=100)),
                ('business', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='automation_rules', to='businesses.business')),
            ],
            options={
                'ordering': ['priority', 'name'],
            },
        ),
        migrations.CreateModel(
            name='AutomationCondition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('field', models.CharField(max_length=128)),
                ('operator', models.CharField(choices=[('eq', 'Equals'), ('gt', 'Greater than'), ('lt', 'Less than'), ('contains', 'Contains'), ('in', 'In')], default='eq', max_length=32)),
                ('value', models.JSONField(blank=True, default=dict)),
                ('rule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='conditions', to='automations.automationrule')),
            ],
        ),
        migrations.CreateModel(
            name='AutomationAction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action_type', models.CharField(choices=[('create_task', 'Create task'), ('assign_manager', 'Assign manager'), ('move_stage', 'Move stage'), ('create_notification', 'Create notification'), ('webhook', 'Webhook'), ('wait', 'Wait'), ('ai_summarize', 'AI summarize'), ('ai_respond', 'AI respond')], max_length=64)),
                ('config', models.JSONField(blank=True, default=dict)),
                ('order', models.PositiveIntegerField(default=0)),
                ('delay_seconds', models.PositiveIntegerField(default=0)),
                ('rule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='actions', to='automations.automationrule')),
            ],
            options={
                'ordering': ['rule', 'order'],
            },
        ),
        migrations.CreateModel(
            name='AutomationRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('trigger_type', models.CharField(max_length=64)),
                ('entity_type', models.CharField(blank=True, max_length=96)),
                ('entity_id', models.CharField(blank=True, max_length=64)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('running', 'Running'), ('success', 'Success'), ('failed', 'Failed'), ('skipped', 'Skipped')], default='pending', max_length=32)),
                ('payload', models.JSONField(blank=True, default=dict)),
                ('error', models.TextField(blank=True)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('business', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='automation_runs', to='businesses.business')),
                ('rule', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='runs', to='automations.automationrule')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='automationrule',
            index=models.Index(fields=['business', 'trigger_type', 'is_active'], name='automations_busines_2d792b_idx'),
        ),
        migrations.AddIndex(
            model_name='automationrun',
            index=models.Index(fields=['business', 'trigger_type', 'created_at'], name='automations_busines_aa86cd_idx'),
        ),
        migrations.AddIndex(
            model_name='automationrun',
            index=models.Index(fields=['status', 'created_at'], name='automations_status_3ca63f_idx'),
        ),
    ]
