# Generated by Django 5.2.14 on 2026-05-13 08:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('automations', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='automationrule',
            name='trigger_type',
            field=models.CharField(choices=[('lead_created', 'Lead created'), ('deal_created', 'Deal created'), ('stage_changed', 'Stage changed'), ('message_received', 'Message received'), ('bot_message_received', 'Bot message received'), ('task_overdue', 'Task overdue'), ('appointment_created', 'Appointment created'), ('appointment_cancelled', 'Appointment cancelled'), ('client_inactive', 'Client inactive'), ('tag_added', 'Tag added'), ('tag_removed', 'Tag removed')], max_length=64),
        ),
    ]
