# Generated by Django 5.2.15 on 2026-07-13 07:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('automations', '0003_automationrun_action_results_automationrun_attempts_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='automationaction',
            name='action_type',
            field=models.CharField(choices=[('create_task', 'Create task'), ('create_follow_up', 'Create follow-up'), ('assign_manager', 'Assign manager'), ('assign_user', 'Assign user'), ('add_note', 'Add note'), ('move_stage', 'Move stage'), ('create_notification', 'Create notification'), ('webhook', 'Webhook'), ('wait', 'Wait'), ('ai_summarize', 'AI summarize'), ('ai_respond', 'AI respond')], max_length=64),
        ),
        migrations.AlterField(
            model_name='automationrule',
            name='trigger_type',
            field=models.CharField(choices=[('lead_created', 'Lead created'), ('lead_status_changed', 'Lead status changed'), ('deal_created', 'Deal created'), ('deal_stage_changed', 'Deal stage changed'), ('stage_changed', 'Stage changed'), ('message_received', 'Message received'), ('bot_message_received', 'Bot message received'), ('conversation_unread', 'Conversation unread'), ('task_overdue', 'Task overdue'), ('appointment_created', 'Appointment created'), ('appointment_cancelled', 'Appointment cancelled'), ('appointment_completed', 'Appointment completed'), ('client_inactive', 'Client inactive'), ('tag_added', 'Tag added'), ('tag_removed', 'Tag removed')], max_length=64),
        ),
        migrations.AlterField(
            model_name='automationrun',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('running', 'Running'), ('success', 'Success'), ('failed', 'Failed'), ('skipped', 'Skipped'), ('cancelled', 'Cancelled')], default='pending', max_length=32),
        ),
    ]
