# Generated by Django 5.2.15 on 2026-07-21 08:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('automations', '0004_alter_automationaction_action_type_and_more'),
        ('businesses', '0005_business_operational_settings'),
    ]

    operations = [
        migrations.AddField(
            model_name='automationrun',
            name='current_action_index',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='automationrun',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('running', 'Running'), ('waiting', 'Waiting'), ('retry_scheduled', 'Retry scheduled'), ('success', 'Success'), ('failed', 'Failed'), ('skipped', 'Skipped'), ('cancelled', 'Cancelled')], default='pending', max_length=32),
        ),
        migrations.AddIndex(
            model_name='automationrun',
            index=models.Index(fields=['status', 'run_after', 'next_retry_at'], name='automations_status_648504_idx'),
        ),
    ]
