# Generated by Django 5.2.14 on 2026-05-14 07:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('businesses', '0001_initial'),
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomFieldDefinition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entity_type', models.CharField(choices=[('client', 'Client'), ('lead', 'Lead'), ('deal', 'Deal'), ('appointment', 'Appointment')], max_length=32)),
                ('key', models.SlugField(max_length=64)),
                ('label', models.CharField(max_length=128)),
                ('field_type', models.CharField(choices=[('text', 'Text'), ('textarea', 'Textarea'), ('number', 'Number'), ('money', 'Money'), ('date', 'Date'), ('datetime', 'Datetime'), ('select', 'Select'), ('multiselect', 'Multiselect'), ('boolean', 'Boolean'), ('phone', 'Phone'), ('email', 'Email'), ('url', 'URL')], default='text', max_length=32)),
                ('options_json', models.JSONField(blank=True, default=dict)),
                ('is_required', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('business', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='custom_field_definitions', to='businesses.business')),
            ],
            options={
                'ordering': ['entity_type', 'sort_order', 'label'],
            },
        ),
        migrations.CreateModel(
            name='CustomFieldValue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entity_type', models.CharField(choices=[('client', 'Client'), ('lead', 'Lead'), ('deal', 'Deal'), ('appointment', 'Appointment')], max_length=32)),
                ('entity_id', models.CharField(max_length=64)),
                ('value_json', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('business', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='custom_field_values', to='businesses.business')),
                ('definition', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='values', to='core.customfielddefinition')),
            ],
            options={
                'ordering': ['definition__sort_order', 'definition__label'],
            },
        ),
        migrations.AddIndex(
            model_name='customfielddefinition',
            index=models.Index(fields=['business', 'entity_type', 'is_active', 'sort_order'], name='core_custom_busines_6f3c6d_idx'),
        ),
        migrations.AddConstraint(
            model_name='customfielddefinition',
            constraint=models.UniqueConstraint(fields=('business', 'entity_type', 'key'), name='unique_custom_field_key_per_entity'),
        ),
        migrations.AddIndex(
            model_name='customfieldvalue',
            index=models.Index(fields=['business', 'entity_type', 'entity_id'], name='core_custom_busines_58fbe0_idx'),
        ),
        migrations.AddConstraint(
            model_name='customfieldvalue',
            constraint=models.UniqueConstraint(fields=('definition', 'entity_type', 'entity_id'), name='unique_custom_field_value_per_entity'),
        ),
    ]
