# Generated by Django 5.2.14 on 2026-05-19 14:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('businesses', '0002_rolepreset_alter_businessmember_role_businessrole_and_more'),
        ('core', '0002_customfielddefinition_customfieldvalue_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ImportJob',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entity_type', models.CharField(choices=[('clients', 'Clients'), ('leads', 'Leads'), ('deals', 'Deals')], default='clients', max_length=32)),
                ('source_file', models.FileField(upload_to='imports/%Y/%m/%d/')),
                ('original_filename', models.CharField(blank=True, max_length=255)),
                ('status', models.CharField(choices=[('uploaded', 'Uploaded'), ('previewed', 'Previewed'), ('imported', 'Imported'), ('failed', 'Failed'), ('cancelled', 'Cancelled')], default='uploaded', max_length=32)),
                ('mapping_json', models.JSONField(blank=True, default=dict)),
                ('preview_json', models.JSONField(blank=True, default=dict)),
                ('duplicates_json', models.JSONField(blank=True, default=dict)),
                ('total_rows', models.PositiveIntegerField(default=0)),
                ('imported_count', models.PositiveIntegerField(default=0)),
                ('error', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('imported_at', models.DateTimeField(blank=True, null=True)),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='import_jobs', to=settings.AUTH_USER_MODEL)),
                ('business', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='import_jobs', to='businesses.business')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['business', 'entity_type', 'status', 'created_at'], name='core_import_busines_438ab8_idx')],
            },
        ),
    ]
