# Generated by Django 5.2.14 on 2026-05-19 15:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('businesses', '0002_rolepreset_alter_businessmember_role_businessrole_and_more'),
        ('core', '0003_importjob'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LoginHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('status', models.CharField(choices=[('success', 'Success'), ('failed', 'Failed')], max_length=32)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='auditlog',
            name='category',
            field=models.CharField(choices=[('data', 'Data'), ('access', 'Access'), ('security', 'Security'), ('system', 'System'), ('integration', 'Integration')], default='data', max_length=32),
        ),
        migrations.AddField(
            model_name='auditlog',
            name='risk_level',
            field=models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('critical', 'Critical')], default='low', max_length=32),
        ),
        migrations.AddIndex(
            model_name='auditlog',
            index=models.Index(fields=['business', 'risk_level', 'created_at'], name='core_auditl_busines_5b0ab1_idx'),
        ),
        migrations.AddIndex(
            model_name='auditlog',
            index=models.Index(fields=['business', 'category', 'created_at'], name='core_auditl_busines_e156e1_idx'),
        ),
        migrations.AddField(
            model_name='loginhistory',
            name='business',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='login_history', to='businesses.business'),
        ),
        migrations.AddField(
            model_name='loginhistory',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='login_history', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='loginhistory',
            index=models.Index(fields=['business', 'created_at'], name='core_loginh_busines_9c8f18_idx'),
        ),
        migrations.AddIndex(
            model_name='loginhistory',
            index=models.Index(fields=['user', 'created_at'], name='core_loginh_user_id_071a0c_idx'),
        ),
        migrations.AddIndex(
            model_name='loginhistory',
            index=models.Index(fields=['status', 'created_at'], name='core_loginh_status_0ad94e_idx'),
        ),
    ]
