# Generated by Django 5.2.14 on 2026-05-19 19:17

import apps.core.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('businesses', '0002_rolepreset_alter_businessmember_role_businessrole_and_more'),
        ('core', '0004_loginhistory_auditlog_category_auditlog_risk_level_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FileAttachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to=apps.core.models.attachment_upload_path)),
                ('original_name', models.CharField(max_length=255)),
                ('content_type', models.CharField(blank=True, max_length=128)),
                ('size', models.PositiveBigIntegerField(default=0)),
                ('entity_type', models.CharField(max_length=64)),
                ('entity_id', models.CharField(max_length=64)),
                ('visibility', models.CharField(choices=[('private', 'Private')], default='private', max_length=32)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('business', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='file_attachments', to='businesses.business')),
                ('uploaded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='file_attachments', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['business', 'entity_type', 'entity_id', 'created_at'], name='core_fileat_busines_7027fa_idx'), models.Index(fields=['uploaded_by', 'created_at'], name='core_fileat_uploade_01b675_idx')],
            },
        ),
    ]
