# Generated by Django 5.2.14 on 2026-05-20 09:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_fileattachment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auditlog',
            name='action',
            field=models.CharField(choices=[('create', 'Create'), ('update', 'Update'), ('delete', 'Delete'), ('download', 'Download'), ('support_access', 'Support access')], max_length=32),
        ),
    ]
