# Generated by Django 5.2.14 on 2026-05-22 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_alter_auditlog_action'),
    ]

    operations = [
        migrations.AddField(
            model_name='importjob',
            name='errors_json',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AlterField(
            model_name='importjob',
            name='entity_type',
            field=models.CharField(choices=[('clients', 'Clients'), ('leads', 'Leads'), ('deals', 'Deals'), ('sales', 'Sales'), ('catalog', 'Catalog')], default='clients', max_length=32),
        ),
    ]
