# Generated by Django 5.2.15 on 2026-07-21 09:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('businesses', '0008_alter_businessinvitation_role_and_more'),
        ('core', '0008_customfielddefinition_permissions_json'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ExportJob',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('entity', 'Entity'), ('analytics_report', 'Analytics report')], max_length=32)),
                ('export_key', models.CharField(max_length=64)),
                ('parameters_json', models.JSONField(blank=True, default=dict)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('running', 'Running'), ('succeeded', 'Succeeded'), ('failed', 'Failed')], default='pending', max_length=32)),
                ('row_count', models.PositiveIntegerField(default=0)),
                ('result_file', models.FileField(blank=True, upload_to='exports/%Y/%m/%d/')),
                ('error', models.TextField(blank=True)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('actor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='export_jobs', to=settings.AUTH_USER_MODEL)),
                ('business', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='export_jobs', to='businesses.business')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['business', 'actor', 'status', 'created_at'], name='core_export_busines_f9ce2f_idx'), models.Index(fields=['business', 'kind', 'export_key', 'created_at'], name='core_export_busines_7a835e_idx')],
            },
        ),
    ]
