# Generated by Django 5.2.15 on 2026-07-23 09:33

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('businesses', '0008_alter_businessinvitation_role_and_more'),
        ('core', '0009_exportjob'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CRMCommandIdempotency',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(max_length=128)),
                ('idempotency_key', models.CharField(max_length=128)),
                ('request_hash', models.CharField(max_length=64)),
                ('status', models.CharField(choices=[('processing', 'Processing'), ('succeeded', 'Succeeded')], default='processing', max_length=32)),
                ('claim_token', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('attempts', models.PositiveIntegerField(default=1)),
                ('response_status', models.PositiveSmallIntegerField(default=200)),
                ('response_json', models.JSONField(blank=True, default=dict)),
                ('resource_type', models.CharField(blank=True, max_length=128)),
                ('resource_id', models.CharField(blank=True, max_length=64)),
                ('locked_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('expires_at', models.DateTimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('actor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='crm_command_idempotency_records', to=settings.AUTH_USER_MODEL)),
                ('business', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='crm_command_idempotency_records', to='businesses.business')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['business', 'created_at'], name='core_crmcom_busines_c5c9f0_idx'), models.Index(fields=['status', 'expires_at'], name='core_crmcom_status_6bcd6a_idx')],
                'constraints': [models.UniqueConstraint(fields=('business', 'actor', 'action', 'idempotency_key'), name='unique_crm_command_idempotency_key')],
            },
        ),
    ]
