# Generated by Django 5.2.14 on 2026-05-11 10:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('businesses', '0001_initial'),
        ('clients', '0001_initial'),
        ('services', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Lead',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('source', models.CharField(choices=[('website', 'Website'), ('telegram', 'Telegram'), ('whatsapp', 'WhatsApp'), ('instagram', 'Instagram'), ('manual', 'Manual'), ('parser', 'Parser'), ('other', 'Other')], default='manual', max_length=32)),
                ('message', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('new', 'New'), ('in_progress', 'In progress'), ('appointment_created', 'Appointment created'), ('contacted', 'Contacted'), ('closed', 'Closed'), ('lost', 'Lost')], default='new', max_length=32)),
                ('business', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='leads', to='businesses.business')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='leads', to='clients.client')),
                ('responsible_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_leads', to=settings.AUTH_USER_MODEL)),
                ('service', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='leads', to='services.service')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
