# Generated by Django 5.2.14 on 2026-05-14 14:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('businesses', '0002_rolepreset_alter_businessmember_role_businessrole_and_more'),
        ('clients', '0002_client_archive_reason_client_archived_at_and_more'),
        ('leads', '0001_initial'),
        ('services', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='lead',
            name='archive_reason',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='lead',
            name='archived_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='lead',
            name='archived_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='archived_leads', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='lead',
            name='is_archived',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='lead',
            name='lost_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='lead',
            name='lost_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lost_leads', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='lead',
            name='lost_reason',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='lead',
            name='previous_status',
            field=models.CharField(blank=True, max_length=32),
        ),
        migrations.AddIndex(
            model_name='lead',
            index=models.Index(fields=['business', 'status', 'is_archived'], name='leads_lead_busines_25912f_idx'),
        ),
    ]
