# Generated by Django 5.2.14 on 2026-05-19 14:34

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('businesses', '0002_rolepreset_alter_businessmember_role_businessrole_and_more'),
        ('clients', '0002_client_archive_reason_client_archived_at_and_more'),
        ('leads', '0002_lead_archive_reason_lead_archived_at_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LeadForm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255)),
                ('public_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('source', models.CharField(choices=[('website', 'Website'), ('telegram', 'Telegram'), ('whatsapp', 'WhatsApp'), ('instagram', 'Instagram'), ('manual', 'Manual'), ('parser', 'Parser'), ('other', 'Other')], default='website', max_length=32)),
                ('success_message', models.CharField(default='Спасибо! Мы скоро свяжемся с вами.', max_length=255)),
                ('is_active', models.BooleanField(default=True)),
                ('business', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lead_forms', to='businesses.business')),
                ('default_responsible_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='default_lead_forms', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='LeadFormField',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('label', models.CharField(max_length=128)),
                ('key', models.SlugField(max_length=64)),
                ('field_type', models.CharField(choices=[('text', 'Text'), ('textarea', 'Textarea'), ('phone', 'Phone'), ('email', 'Email'), ('select', 'Select')], default='text', max_length=32)),
                ('placeholder', models.CharField(blank=True, max_length=255)),
                ('options_json', models.JSONField(blank=True, default=dict)),
                ('is_required', models.BooleanField(default=False)),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('form', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fields', to='leads.leadform')),
            ],
            options={
                'ordering': ['sort_order', 'label'],
            },
        ),
        migrations.CreateModel(
            name='LeadFormSubmission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payload_json', models.JSONField(blank=True, default=dict)),
                ('utm_json', models.JSONField(blank=True, default=dict)),
                ('duplicate_json', models.JSONField(blank=True, default=dict)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('business', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lead_form_submissions', to='businesses.business')),
                ('client', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lead_form_submissions', to='clients.client')),
                ('form', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='submissions', to='leads.leadform')),
                ('lead', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='form_submissions', to='leads.lead')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='leadform',
            index=models.Index(fields=['business', 'is_active', 'created_at'], name='leads_leadf_busines_31fa4e_idx'),
        ),
        migrations.AddIndex(
            model_name='leadform',
            index=models.Index(fields=['public_id', 'is_active'], name='leads_leadf_public__df6d4c_idx'),
        ),
        migrations.AddConstraint(
            model_name='leadformfield',
            constraint=models.UniqueConstraint(fields=('form', 'key'), name='unique_lead_form_field_key'),
        ),
        migrations.AddIndex(
            model_name='leadformsubmission',
            index=models.Index(fields=['business', 'form', 'created_at'], name='leads_leadf_busines_31525b_idx'),
        ),
        migrations.AddIndex(
            model_name='leadformsubmission',
            index=models.Index(fields=['lead', 'created_at'], name='leads_leadf_lead_id_b73ea2_idx'),
        ),
    ]
