# Generated by Django 5.2.14 on 2026-05-22 15:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('businesses', '0002_rolepreset_alter_businessmember_role_businessrole_and_more'),
        ('clients', '0002_client_archive_reason_client_archived_at_and_more'),
        ('leads', '0003_leadform_leadformfield_leadformsubmission_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LeadFormSubmissionError',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('public_id', models.CharField(blank=True, max_length=128)),
                ('landing_id', models.CharField(blank=True, max_length=128)),
                ('page_url', models.URLField(blank=True)),
                ('page_domain', models.CharField(blank=True, max_length=255)),
                ('payload_json', models.JSONField(blank=True, default=dict)),
                ('error_message', models.TextField()),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='leadform',
            name='landing_domain',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='leadform',
            name='landing_id',
            field=models.CharField(blank=True, db_index=True, max_length=128),
        ),
        migrations.AddField(
            model_name='leadform',
            name='preview_url',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='leadformsubmission',
            name='landing_id',
            field=models.CharField(blank=True, max_length=128),
        ),
        migrations.AddField(
            model_name='leadformsubmission',
            name='page_domain',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='leadformsubmission',
            name='page_url',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='leadformsubmission',
            name='source_context_json',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AlterField(
            model_name='lead',
            name='source',
            field=models.CharField(choices=[('website', 'Website'), ('landing', 'Landing'), ('telegram', 'Telegram'), ('whatsapp', 'WhatsApp'), ('instagram', 'Instagram'), ('manual', 'Manual'), ('parser', 'Parser'), ('other', 'Other')], default='manual', max_length=32),
        ),
        migrations.AlterField(
            model_name='leadform',
            name='source',
            field=models.CharField(choices=[('website', 'Website'), ('landing', 'Landing'), ('telegram', 'Telegram'), ('whatsapp', 'WhatsApp'), ('instagram', 'Instagram'), ('manual', 'Manual'), ('parser', 'Parser'), ('other', 'Other')], default='website', max_length=32),
        ),
        migrations.AddIndex(
            model_name='leadformsubmission',
            index=models.Index(fields=['business', 'landing_id', 'created_at'], name='leads_leadf_busines_449daf_idx'),
        ),
        migrations.AddIndex(
            model_name='leadformsubmission',
            index=models.Index(fields=['business', 'page_domain', 'created_at'], name='leads_leadf_busines_73e42c_idx'),
        ),
        migrations.AddConstraint(
            model_name='leadform',
            constraint=models.UniqueConstraint(condition=models.Q(('landing_id', ''), _negated=True), fields=('landing_id',), name='unique_active_lead_form_landing_id'),
        ),
        migrations.AddField(
            model_name='leadformsubmissionerror',
            name='business',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lead_form_submission_errors', to='businesses.business'),
        ),
        migrations.AddField(
            model_name='leadformsubmissionerror',
            name='form',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='submission_errors', to='leads.leadform'),
        ),
        migrations.AddIndex(
            model_name='leadformsubmissionerror',
            index=models.Index(fields=['business', 'created_at'], name='leads_leadf_busines_e46388_idx'),
        ),
        migrations.AddIndex(
            model_name='leadformsubmissionerror',
            index=models.Index(fields=['public_id', 'created_at'], name='leads_leadf_public__0650ed_idx'),
        ),
        migrations.AddIndex(
            model_name='leadformsubmissionerror',
            index=models.Index(fields=['landing_id', 'created_at'], name='leads_leadf_landing_9ff8f8_idx'),
        ),
    ]
