# Generated by Django 5.2.14 on 2026-06-16 08:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0006_lead_list_filter_indexes'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='lead',
            name='lead_lead_busi_client_arch_idx',
        ),
        migrations.RemoveIndex(
            model_name='lead',
            name='lead_busi_source_arch_idx',
        ),
        migrations.RemoveIndex(
            model_name='lead',
            name='lead_busi_resp_status_idx',
        ),
        migrations.RemoveIndex(
            model_name='lead',
            name='lead_busi_created_idx',
        ),
        migrations.RemoveIndex(
            model_name='lead',
            name='lead_busi_updated_idx',
        ),
    ]
