# Generated by Django 5.2.15 on 2026-07-21 09:44

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('businesses', '0008_alter_businessinvitation_role_and_more'),
        ('clients', '0005_client_source_attribution'),
        ('leads', '0007_remove_lead_lead_lead_busi_client_arch_idx_and_more'),
        ('services', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='lead',
            index=models.Index(fields=['business', 'responsible_user', 'created_at'], name='leads_lead_busines_39f06b_idx'),
        ),
    ]
