# Generated by Django 5.2.17 on 2026-09-14 13:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('businesses', '0010_alter_businessinvitation_role_and_more'),
        ('clients', '0005_client_source_attribution'),
        ('crm', '0010_pipeline_stage_canonicalization'),
        ('scheduling', '0007_appointment_scheduling__busines_e1d6c2_idx_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('receipt', 'Receipt'), ('refund', 'Refund')], max_length=16)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=14)),
                ('refunded_amount', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('currency', models.CharField(max_length=8)),
                ('occurred_at', models.DateTimeField()),
                ('method', models.CharField(choices=[('cash', 'Cash'), ('card', 'Card'), ('transfer', 'Bank transfer'), ('other', 'Other')], max_length=16)),
                ('source', models.CharField(default='manual', editable=False, max_length=24)),
                ('note', models.CharField(blank=True, max_length=1000)),
                ('reason', models.CharField(blank=True, max_length=500)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('submission_id', models.UUIDField()),
                ('request_hash', models.CharField(editable=False, max_length=64)),
                ('appointment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='payments', to='scheduling.appointment')),
                ('business', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='client_payments', to='businesses.business')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='payments', to='clients.client')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='recorded_client_payments', to=settings.AUTH_USER_MODEL)),
                ('deal', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='payments', to='crm.deal')),
                ('original', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='refunds', to='payments.payment')),
            ],
            options={
                'ordering': ['-occurred_at', '-id'],
                'indexes': [models.Index(fields=['business', 'occurred_at', 'id'], name='payments_pa_busines_39d2b5_idx'), models.Index(fields=['business', 'client', 'occurred_at'], name='payments_pa_busines_da1043_idx')],
                'constraints': [models.UniqueConstraint(fields=('business', 'submission_id'), name='payment_submission_unique'), models.CheckConstraint(condition=models.Q(('amount__gt', 0)), name='payment_amount_positive'), models.CheckConstraint(condition=models.Q(('refunded_amount__gte', 0), ('refunded_amount__lte', models.F('amount'))), name='payment_refund_bounded'), models.CheckConstraint(condition=models.Q(models.Q(('kind', 'receipt'), ('original__isnull', True)), models.Q(('kind', 'refund'), ('original__isnull', False), ('refunded_amount', 0)), _connector='OR'), name='payment_original_matches_kind'), models.CheckConstraint(condition=models.Q(('deal__isnull', True), ('appointment__isnull', True), _connector='OR'), name='payment_single_link')],
            },
        ),
    ]
