# Generated by Codex on 2026-05-28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("activities", "0002_segment_segmentfilter_and_more"),
        ("businesses", "0004_businessinvitation"),
        ("clients", "0002_client_archive_reason_client_archived_at_and_more"),
        ("notifications", "0003_notification_recipient"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="OutreachTemplate",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=160)),
                ("channel", models.CharField(choices=[("telegram", "Telegram"), ("whatsapp", "WhatsApp")], max_length=32)),
                ("body", models.TextField()),
                ("is_active", models.BooleanField(default=True)),
                ("business", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="outreach_templates", to="businesses.business")),
                ("created_by", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="created_outreach_templates", to=settings.AUTH_USER_MODEL)),
            ],
            options={"ordering": ["-updated_at"]},
        ),
        migrations.CreateModel(
            name="OutreachCampaign",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=180)),
                ("channel", models.CharField(choices=[("telegram", "Telegram"), ("whatsapp", "WhatsApp")], max_length=32)),
                ("status", models.CharField(choices=[("draft", "Draft"), ("ready", "Ready"), ("scheduled", "Scheduled"), ("running", "Running"), ("sent", "Sent"), ("cancelled", "Cancelled")], default="draft", max_length=32)),
                ("audience_type", models.CharField(choices=[("all_clients", "All clients"), ("segment", "Segment"), ("manual", "Manual")], default="all_clients", max_length=32)),
                ("message_text", models.TextField()),
                ("scheduled_at", models.DateTimeField(blank=True, null=True)),
                ("started_at", models.DateTimeField(blank=True, null=True)),
                ("finished_at", models.DateTimeField(blank=True, null=True)),
                ("business", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="outreach_campaigns", to="businesses.business")),
                ("created_by", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="created_outreach_campaigns", to=settings.AUTH_USER_MODEL)),
                ("segment", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="outreach_campaigns", to="activities.segment")),
                ("template", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="campaigns", to="outreach.outreachtemplate")),
            ],
            options={"ordering": ["-updated_at"]},
        ),
        migrations.CreateModel(
            name="OutreachRecipient",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("status", models.CharField(choices=[("queued", "Queued"), ("pending", "Pending"), ("sent", "Sent"), ("failed", "Failed"), ("skipped", "Skipped"), ("cancelled", "Cancelled")], default="queued", max_length=32)),
                ("recipient_id", models.CharField(blank=True, max_length=128)),
                ("personalized_text", models.TextField(blank=True)),
                ("error", models.TextField(blank=True)),
                ("sent_at", models.DateTimeField(blank=True, null=True)),
                ("business", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="outreach_recipients", to="businesses.business")),
                ("campaign", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="recipients", to="outreach.outreachcampaign")),
                ("client", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="outreach_recipients", to="clients.client")),
                ("notification", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="outreach_recipients", to="notifications.notification")),
            ],
            options={"ordering": ["campaign", "client_id"]},
        ),
        migrations.AddIndex(model_name="outreachtemplate", index=models.Index(fields=["business", "channel", "is_active"], name="outreach_ou_busines_6bec35_idx")),
        migrations.AddIndex(model_name="outreachcampaign", index=models.Index(fields=["business", "status", "channel"], name="outreach_ou_busines_2f6332_idx")),
        migrations.AddIndex(model_name="outreachcampaign", index=models.Index(fields=["business", "audience_type"], name="outreach_ou_busines_2a46a5_idx")),
        migrations.AddIndex(model_name="outreachrecipient", index=models.Index(fields=["business", "status"], name="outreach_ou_busines_d3f861_idx")),
        migrations.AddIndex(model_name="outreachrecipient", index=models.Index(fields=["campaign", "status"], name="outreach_ou_campaig_2d2d11_idx")),
        migrations.AddConstraint(model_name="outreachrecipient", constraint=models.UniqueConstraint(fields=("campaign", "client"), name="unique_outreach_recipient_per_campaign_client")),
    ]
