# Generated by Codex on 2026-05-28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("businesses", "0004_businessinvitation"),
        ("clients", "0002_client_archive_reason_client_archived_at_and_more"),
        ("outreach", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="outreachtemplate",
            name="external_template_name",
            field=models.CharField(blank=True, max_length=160),
        ),
        migrations.AddField(
            model_name="outreachtemplate",
            name="is_approved",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="outreachtemplate",
            name="language_code",
            field=models.CharField(default="ru", max_length=16),
        ),
        migrations.AddField(
            model_name="outreachcampaign",
            name="batch_size",
            field=models.PositiveIntegerField(default=100),
        ),
        migrations.AddField(
            model_name="outreachcampaign",
            name="campaign_type",
            field=models.CharField(choices=[("service", "Service"), ("marketing", "Marketing"), ("transactional", "Transactional")], default="service", max_length=32),
        ),
        migrations.AddField(
            model_name="outreachcampaign",
            name="rate_limit_per_minute",
            field=models.PositiveIntegerField(default=60),
        ),
        migrations.AddField(
            model_name="outreachcampaign",
            name="require_opt_in",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="outreachcampaign",
            name="whatsapp_template_language",
            field=models.CharField(default="ru", max_length=16),
        ),
        migrations.AddField(
            model_name="outreachcampaign",
            name="whatsapp_template_name",
            field=models.CharField(blank=True, max_length=160),
        ),
        migrations.AddField(
            model_name="outreachcampaign",
            name="whatsapp_template_status",
            field=models.CharField(choices=[("not_required", "Not required"), ("draft", "Draft"), ("pending", "Pending"), ("approved", "Approved"), ("rejected", "Rejected")], default="not_required", max_length=32),
        ),
        migrations.AddField(
            model_name="outreachrecipient",
            name="skipped_reason",
            field=models.CharField(blank=True, max_length=160),
        ),
        migrations.CreateModel(
            name="OutreachConsent",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("channel", models.CharField(choices=[("telegram", "Telegram"), ("whatsapp", "WhatsApp")], max_length=32)),
                ("status", models.CharField(choices=[("opted_in", "Opted in"), ("opted_out", "Opted out"), ("unknown", "Unknown")], default="unknown", max_length=32)),
                ("source", models.CharField(blank=True, max_length=96)),
                ("note", models.TextField(blank=True)),
                ("opted_in_at", models.DateTimeField(blank=True, null=True)),
                ("opted_out_at", models.DateTimeField(blank=True, null=True)),
                ("business", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="outreach_consents", to="businesses.business")),
                ("client", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="outreach_consents", to="clients.client")),
            ],
            options={"ordering": ["client_id", "channel"]},
        ),
        migrations.AddIndex(model_name="outreachcampaign", index=models.Index(fields=["business", "campaign_type"], name="outreach_ou_busines_d9361d_idx")),
        migrations.AddIndex(model_name="outreachconsent", index=models.Index(fields=["business", "channel", "status"], name="outreach_ou_busines_25f507_idx")),
        migrations.AddConstraint(model_name="outreachconsent", constraint=models.UniqueConstraint(fields=("business", "client", "channel"), name="unique_outreach_consent_per_client_channel")),
    ]
