# Generated by Django 5.2.14 on 2026-05-28 07:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('outreach', '0002_production_safety'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='outreachcampaign',
            new_name='outreach_ou_busines_5dee11_idx',
            old_name='outreach_ou_busines_2f6332_idx',
        ),
        migrations.RenameIndex(
            model_name='outreachcampaign',
            new_name='outreach_ou_busines_dc2eac_idx',
            old_name='outreach_ou_busines_2a46a5_idx',
        ),
        migrations.RenameIndex(
            model_name='outreachcampaign',
            new_name='outreach_ou_busines_d723a0_idx',
            old_name='outreach_ou_busines_d9361d_idx',
        ),
        migrations.RenameIndex(
            model_name='outreachconsent',
            new_name='outreach_ou_busines_561a55_idx',
            old_name='outreach_ou_busines_25f507_idx',
        ),
        migrations.RenameIndex(
            model_name='outreachrecipient',
            new_name='outreach_ou_busines_d10e8a_idx',
            old_name='outreach_ou_busines_d3f861_idx',
        ),
        migrations.RenameIndex(
            model_name='outreachrecipient',
            new_name='outreach_ou_campaig_a99a2e_idx',
            old_name='outreach_ou_campaig_2d2d11_idx',
        ),
        migrations.RenameIndex(
            model_name='outreachtemplate',
            new_name='outreach_ou_busines_70e278_idx',
            old_name='outreach_ou_busines_6bec35_idx',
        ),
        migrations.AddField(
            model_name='outreachconsent',
            name='evidence_json',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='outreachrecipient',
            name='error_code',
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AddField(
            model_name='outreachrecipient',
            name='provider_result',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
