# Generated by Django 5.2.14 on 2026-05-11 16:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('businesses', '0001_initial'),
        ('clients', '0001_initial'),
        ('leads', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Pipeline',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255)),
                ('slug', models.SlugField()),
                ('entity_type', models.CharField(choices=[('deal', 'Deal')], default='deal', max_length=32)),
                ('is_default', models.BooleanField(default=False)),
                ('template_key', models.CharField(blank=True, max_length=64)),
                ('business', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pipelines', to='businesses.business')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='PipelineStage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255)),
                ('order', models.PositiveIntegerField(default=0)),
                ('color', models.CharField(default='#2563eb', max_length=24)),
                ('probability', models.PositiveSmallIntegerField(default=0)),
                ('sla_minutes', models.PositiveIntegerField(blank=True, null=True)),
                ('is_won', models.BooleanField(default=False)),
                ('is_lost', models.BooleanField(default=False)),
                ('business', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pipeline_stages', to='businesses.business')),
                ('pipeline', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stages', to='crm.pipeline')),
            ],
            options={
                'ordering': ['pipeline', 'order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Deal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=255)),
                ('amount', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('currency', models.CharField(default='KZT', max_length=8)),
                ('probability', models.PositiveSmallIntegerField(default=0)),
                ('expected_close_at', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('open', 'Open'), ('won', 'Won'), ('lost', 'Lost')], default='open', max_length=32)),
                ('source', models.CharField(blank=True, max_length=64)),
                ('notes', models.TextField(blank=True)),
                ('business', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deals', to='businesses.business')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='deals', to='clients.client')),
                ('lead', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='deals', to='leads.lead')),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='owned_deals', to=settings.AUTH_USER_MODEL)),
                ('pipeline', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='deals', to='crm.pipeline')),
                ('stage', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='deals', to='crm.pipelinestage')),
            ],
            options={
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='StageTransition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('required_permission', models.CharField(blank=True, max_length=128)),
                ('conditions', models.JSONField(blank=True, default=dict)),
                ('is_active', models.BooleanField(default=True)),
                ('business', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stage_transitions', to='businesses.business')),
                ('from_stage', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='outgoing_transitions', to='crm.pipelinestage')),
                ('pipeline', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transitions', to='crm.pipeline')),
                ('to_stage', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='incoming_transitions', to='crm.pipelinestage')),
            ],
            options={
                'ordering': ['pipeline', 'from_stage__order', 'to_stage__order'],
            },
        ),
        migrations.AddConstraint(
            model_name='pipeline',
            constraint=models.UniqueConstraint(fields=('business', 'slug'), name='unique_pipeline_slug_per_business'),
        ),
        migrations.AddIndex(
            model_name='pipelinestage',
            index=models.Index(fields=['business', 'pipeline', 'order'], name='crm_pipelin_busines_f1affc_idx'),
        ),
        migrations.AddConstraint(
            model_name='pipelinestage',
            constraint=models.UniqueConstraint(fields=('pipeline', 'name'), name='unique_stage_name_per_pipeline'),
        ),
        migrations.AddIndex(
            model_name='deal',
            index=models.Index(fields=['business', 'pipeline', 'stage'], name='crm_deal_busines_b0f00e_idx'),
        ),
        migrations.AddIndex(
            model_name='deal',
            index=models.Index(fields=['business', 'status', 'updated_at'], name='crm_deal_busines_6fca3e_idx'),
        ),
        migrations.AddIndex(
            model_name='deal',
            index=models.Index(fields=['owner', 'updated_at'], name='crm_deal_owner_i_c2e55e_idx'),
        ),
        migrations.AddConstraint(
            model_name='stagetransition',
            constraint=models.UniqueConstraint(fields=('pipeline', 'from_stage', 'to_stage'), name='unique_pipeline_transition'),
        ),
    ]
