# Generated by Django 5.2.14 on 2026-05-14 08:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0002_default_pipeline'),
    ]

    operations = [
        migrations.AddField(
            model_name='deal',
            name='lost_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='deal',
            name='lost_reason',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='deal',
            name='next_action_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='deal',
            name='stage_entered_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='deal',
            name='won_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='pipelinestage',
            name='allowed_roles_json',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='pipelinestage',
            name='required_fields_json',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
