# Generated by Django 5.2.14 on 2026-05-14 14:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('businesses', '0002_rolepreset_alter_businessmember_role_businessrole_and_more'),
        ('clients', '0002_client_archive_reason_client_archived_at_and_more'),
        ('crm', '0003_deal_lost_at_deal_lost_reason_deal_next_action_at_and_more'),
        ('leads', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='deal',
            name='archive_reason',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='deal',
            name='archived_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='deal',
            name='archived_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='archived_deals', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='deal',
            name='is_archived',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='deal',
            name='lost_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lost_deals', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='deal',
            name='previous_stage',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='previous_deals', to='crm.pipelinestage'),
        ),
        migrations.AddField(
            model_name='deal',
            name='previous_status',
            field=models.CharField(blank=True, max_length=32),
        ),
        migrations.AddIndex(
            model_name='deal',
            index=models.Index(fields=['business', 'is_archived', 'updated_at'], name='crm_deal_busines_e5cbe1_idx'),
        ),
    ]
