# Generated by Django 5.2.14 on 2026-06-16 08:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0005_deal_client_indexes'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='deal',
            name='crm_deal_busi_client_arch_idx',
        ),
    ]
