# Generated by Django 5.2.15 on 2026-07-09 06:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('businesses', '0005_business_operational_settings'),
        ('crm', '0006_remove_deal_crm_deal_busi_client_arch_idx'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DealStageHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('from_status', models.CharField(blank=True, max_length=32)),
                ('to_status', models.CharField(blank=True, max_length=32)),
                ('amount_before', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('amount_after', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('source', models.CharField(blank=True, max_length=64)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='deal_stage_history', to=settings.AUTH_USER_MODEL)),
                ('business', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deal_stage_history', to='businesses.business')),
                ('deal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stage_history', to='crm.deal')),
                ('from_stage', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='deal_stage_history_from', to='crm.pipelinestage')),
                ('to_stage', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='deal_stage_history_to', to='crm.pipelinestage')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['business', 'deal', 'created_at'], name='crm_dealsta_busines_ca81d0_idx'), models.Index(fields=['business', 'from_stage', 'to_stage', 'created_at'], name='crm_dealsta_busines_56fc68_idx'), models.Index(fields=['actor', 'created_at'], name='crm_dealsta_actor_i_7baa06_idx')],
            },
        ),
    ]
