# Generated by Django 5.2.15 on 2026-07-09 06:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('businesses', '0005_business_operational_settings'),
        ('crm', '0007_dealstagehistory'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DealValueHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('amount_before', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('amount_after', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('currency_before', models.CharField(blank=True, max_length=8)),
                ('currency_after', models.CharField(blank=True, max_length=8)),
                ('source', models.CharField(blank=True, max_length=64)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='deal_value_history', to=settings.AUTH_USER_MODEL)),
                ('business', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deal_value_history', to='businesses.business')),
                ('deal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='value_history', to='crm.deal')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['business', 'deal', 'created_at'], name='crm_dealval_busines_997e25_idx'), models.Index(fields=['actor', 'created_at'], name='crm_dealval_actor_i_077e7c_idx')],
            },
        ),
    ]
