# Generated by Django 5.2.15 on 2026-07-21 09:44

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('businesses', '0008_alter_businessinvitation_role_and_more'),
        ('clients', '0005_client_source_attribution'),
        ('crm', '0008_dealvaluehistory'),
        ('leads', '0007_remove_lead_lead_lead_busi_client_arch_idx_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='deal',
            index=models.Index(fields=['business', 'owner', 'created_at'], name='crm_deal_busines_b4fdd1_idx'),
        ),
    ]
