# Generated by Django 5.2.14 on 2026-05-14 14:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('businesses', '0002_rolepreset_alter_businessmember_role_businessrole_and_more'),
        ('clients', '0002_client_archive_reason_client_archived_at_and_more'),
        ('leads', '0002_lead_archive_reason_lead_archived_at_and_more'),
        ('scheduling', '0001_initial'),
        ('services', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='archive_reason',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='appointment',
            name='archived_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='appointment',
            name='archived_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='archived_appointments', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='appointment',
            name='is_archived',
            field=models.BooleanField(default=False),
        ),
        migrations.AddIndex(
            model_name='appointment',
            index=models.Index(fields=['business', 'is_archived', 'start_at'], name='scheduling__busines_4a3f07_idx'),
        ),
    ]
