# Generated by Django 5.2.15 on 2026-07-14 11:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('businesses', '0005_business_operational_settings'),
        ('scheduling', '0005_remove_appointment_sched_appoint_busi_client_arch_idx'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='resource',
            name='linked_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='scheduled_resources', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='resource',
            index=models.Index(fields=['business', 'linked_user'], name='sched_res_bus_user_idx'),
        ),
    ]
