# Generated by Django 5.2.15 on 2026-07-21 09:44

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('businesses', '0008_alter_businessinvitation_role_and_more'),
        ('clients', '0005_client_source_attribution'),
        ('leads', '0008_lead_leads_lead_busines_39f06b_idx'),
        ('scheduling', '0006_resource_linked_user'),
        ('services', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='appointment',
            index=models.Index(fields=['business', 'lead', 'status'], name='scheduling__busines_e1d6c2_idx'),
        ),
        migrations.AddIndex(
            model_name='appointment',
            index=models.Index(fields=['business', 'created_at'], name='scheduling__busines_89c18c_idx'),
        ),
    ]
