# Generated by Django 5.2.17 on 2026-09-21 14:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('businesses', '0010_alter_businessinvitation_role_and_more'),
        ('scheduling', '0007_appointment_scheduling__busines_e1d6c2_idx_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ScheduleException',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('date', models.DateField()),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('is_day_off', models.BooleanField(default=False)),
                ('business', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schedule_exceptions', to='businesses.business')),
                ('resource', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schedule_exceptions', to='scheduling.resource')),
            ],
            options={
                'ordering': ['date', 'id'],
                'constraints': [models.UniqueConstraint(fields=('resource', 'date'), name='unique_resource_schedule_date'), models.CheckConstraint(condition=models.Q(('start_time__lt', models.F('end_time'))), name='schedule_exception_time_order')],
            },
        ),
    ]
