# Generated by Django 5.2.14 on 2026-05-13 11:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bots', '0002_public_widget_ids'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='botconversation',
            name='assigned_to',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_bot_conversations', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='botconversation',
            name='bot_enabled',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='botconversation',
            name='external_thread_id',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='botconversation',
            name='handoff_reason',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='botconversation',
            name='handoff_required',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='botconversation',
            name='last_inbound_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='botconversation',
            name='last_message_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='botconversation',
            name='last_outbound_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='botconversation',
            name='metadata_json',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='botconversation',
            name='priority',
            field=models.CharField(choices=[('low', 'Low'), ('normal', 'Normal'), ('high', 'High'), ('urgent', 'Urgent')], default='normal', max_length=32),
        ),
        migrations.AddField(
            model_name='botconversation',
            name='unread_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='botmessage',
            name='delivered_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='botmessage',
            name='error_text',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='botmessage',
            name='external_message_id',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='botmessage',
            name='read_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='botmessage',
            name='sender_type',
            field=models.CharField(choices=[('client', 'Client'), ('bot', 'Bot'), ('manager', 'Manager'), ('system', 'System'), ('ai', 'AI')], default='client', max_length=32),
        ),
        migrations.AddField(
            model_name='botmessage',
            name='sent_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
