# Generated by Django 5.2.14 on 2026-05-14 14:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bots', '0003_botconversation_assigned_to_and_more'),
        ('crm', '0003_deal_lost_at_deal_lost_reason_deal_next_action_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='botconversation',
            name='deal',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bot_conversations', to='crm.deal'),
        ),
    ]
