# Generated by Django 5.2.14 on 2026-06-16 08:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bots', '0006_botconversation_client_indexes'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='botconversation',
            name='bots_botconv_busi_client_arch_idx',
        ),
    ]
