# Generated by Django 5.2.15 on 2026-07-14 13:56

from django.db import migrations, models


def preserve_duplicate_external_message_ids(apps, schema_editor):
    BotMessage = apps.get_model("bots", "BotMessage")
    seen = set()
    queryset = (
        BotMessage.objects.exclude(external_message_id="")
        .order_by("conversation_id", "direction", "external_message_id", "id")
    )
    for message in queryset.iterator():
        key = (message.conversation_id, message.direction, message.external_message_id)
        if key not in seen:
            seen.add(key)
            continue

        payload = dict(message.payload_json or {})
        payload.setdefault("legacy_external_message_id", message.external_message_id)
        suffix = f":duplicate:{message.id}"
        message.external_message_id = f"{message.external_message_id[:255 - len(suffix)]}{suffix}"
        message.payload_json = payload
        message.save(update_fields=["external_message_id", "payload_json"])


class Migration(migrations.Migration):

    dependencies = [
        ('bots', '0007_remove_botconversation_bots_botconv_busi_client_arch_idx'),
    ]

    operations = [
        migrations.RunPython(preserve_duplicate_external_message_ids, migrations.RunPython.noop),
        migrations.AddConstraint(
            model_name='botmessage',
            constraint=models.UniqueConstraint(condition=models.Q(('external_message_id', ''), _negated=True), fields=('conversation', 'direction', 'external_message_id'), name='unique_bot_message_external_delivery'),
        ),
    ]
