# Generated by Django 5.2.15 on 2026-07-21 09:44

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bots', '0008_botmessage_unique_bot_message_external_delivery'),
        ('businesses', '0008_alter_businessinvitation_role_and_more'),
        ('clients', '0005_client_source_attribution'),
        ('crm', '0008_dealvaluehistory'),
        ('leads', '0007_remove_lead_lead_lead_busi_client_arch_idx_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='botconversation',
            index=models.Index(fields=['business', 'status', 'is_archived', 'updated_at'], name='bots_botcon_busines_81d379_idx'),
        ),
        migrations.AddIndex(
            model_name='botconversation',
            index=models.Index(fields=['business', 'assigned_to', 'status', 'updated_at'], name='bots_botcon_busines_e16f97_idx'),
        ),
        migrations.AddIndex(
            model_name='botconversation',
            index=models.Index(fields=['business', 'handoff_required', 'last_inbound_at'], name='bots_botcon_busines_2b8459_idx'),
        ),
        migrations.AddIndex(
            model_name='botmessage',
            index=models.Index(fields=['conversation', 'created_at'], name='bots_botmes_convers_9c083c_idx'),
        ),
    ]
