# Generated by Django 5.2.15 on 2026-07-23 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bots', '0009_botconversation_bots_botcon_busines_81d379_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='botmessage',
            name='delivery_attempts',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='botmessage',
            name='delivery_idempotency_key',
            field=models.CharField(blank=True, max_length=128),
        ),
        migrations.AddField(
            model_name='botmessage',
            name='delivery_last_retry_key',
            field=models.CharField(blank=True, max_length=128),
        ),
        migrations.AddField(
            model_name='botmessage',
            name='delivery_locked_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='botmessage',
            name='delivery_max_attempts',
            field=models.PositiveIntegerField(default=5),
        ),
        migrations.AddField(
            model_name='botmessage',
            name='delivery_next_retry_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='botmessage',
            name='delivery_request_hash',
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AlterField(
            model_name='botmessage',
            name='status',
            field=models.CharField(choices=[('received', 'Received'), ('queued', 'Queued'), ('delivering', 'Delivering'), ('retry_scheduled', 'Retry scheduled'), ('sent', 'Sent'), ('failed', 'Failed')], default='received', max_length=32),
        ),
        migrations.AddIndex(
            model_name='botmessage',
            index=models.Index(fields=['status', 'delivery_next_retry_at', 'created_at'], name='bots_botmes_status_344643_idx'),
        ),
        migrations.AddConstraint(
            model_name='botmessage',
            constraint=models.UniqueConstraint(condition=models.Q(('delivery_idempotency_key', ''), _negated=True), fields=('conversation', 'delivery_idempotency_key'), name='unique_outbound_message_idempotency_key'),
        ),
    ]
