import { cn } from "../../lib/cn";

const styles: Record<string, string> = {
  new: "bg-sky-50 text-sky-700 ring-sky-200",
  in_progress: "bg-amber-50 text-amber-700 ring-amber-200",
  appointment_created: "bg-emerald-50 text-emerald-700 ring-emerald-200",
  contacted: "bg-cyan-50 text-cyan-700 ring-cyan-200",
  closed: "bg-slate-100 text-slate-700 ring-slate-200",
  lost: "bg-red-50 text-red-700 ring-red-200",
  created: "bg-sky-50 text-sky-700 ring-sky-200",
  confirmed: "bg-emerald-50 text-emerald-700 ring-emerald-200",
  cancelled: "bg-red-50 text-red-700 ring-red-200",
  rescheduled: "bg-violet-50 text-violet-700 ring-violet-200",
  completed: "bg-slate-100 text-slate-700 ring-slate-200",
  done: "bg-emerald-50 text-emerald-700 ring-emerald-200",
  no_show: "bg-orange-50 text-orange-700 ring-orange-200",
  active: "bg-emerald-50 text-emerald-700 ring-emerald-200",
  inactive: "bg-slate-100 text-slate-700 ring-slate-200",
  trial: "bg-cyan-50 text-cyan-700 ring-cyan-200",
  blocked: "bg-red-50 text-red-700 ring-red-200",
  draft: "bg-slate-100 text-slate-700 ring-slate-200",
  paused: "bg-amber-50 text-amber-700 ring-amber-200",
  error: "bg-red-50 text-red-700 ring-red-200",
  open: "bg-sky-50 text-sky-700 ring-sky-200",
  archived: "bg-slate-100 text-slate-700 ring-slate-200",
  received: "bg-cyan-50 text-cyan-700 ring-cyan-200",
  queued: "bg-amber-50 text-amber-700 ring-amber-200",
  pending: "bg-amber-50 text-amber-700 ring-amber-200",
  sent: "bg-emerald-50 text-emerald-700 ring-emerald-200",
  failed: "bg-red-50 text-red-700 ring-red-200",
  low: "bg-slate-100 text-slate-700 ring-slate-200",
  normal: "bg-cyan-50 text-cyan-700 ring-cyan-200",
  high: "bg-amber-50 text-amber-700 ring-amber-200",
  urgent: "bg-red-50 text-red-700 ring-red-200",
  friendly: "bg-cyan-50 text-cyan-700 ring-cyan-200",
  expert: "bg-indigo-50 text-indigo-700 ring-indigo-200",
  formal: "bg-slate-100 text-slate-700 ring-slate-200",
  sales: "bg-emerald-50 text-emerald-700 ring-emerald-200",
  support: "bg-violet-50 text-violet-700 ring-violet-200",
};

const labels: Record<string, string> = {
  new: "Новая",
  in_progress: "В работе",
  appointment_created: "Записан",
  contacted: "Связались",
  closed: "Закрыта",
  lost: "Потеряна",
  created: "Создана",
  confirmed: "Подтверждена",
  cancelled: "Отменена",
  rescheduled: "Перенесена",
  completed: "Завершена",
  done: "Готово",
  no_show: "Не пришёл",
  active: "Активен",
  inactive: "Неактивен",
  trial: "Пробный",
  blocked: "Заблокирован",
  draft: "Черновик",
  paused: "Пауза",
  error: "Ошибка",
  open: "Открыт",
  archived: "Архив",
  received: "Получено",
  queued: "В очереди",
  pending: "Ожидает",
  sent: "Отправлено",
  failed: "Ошибка",
  low: "Низкая",
  normal: "Обычная",
  high: "Высокая",
  urgent: "Срочная",
  friendly: "Friendly",
  expert: "Expert",
  formal: "Formal",
  sales: "Sales",
  support: "Support",
};

export function StatusBadge({ status }: { status: string }) {
  return (
    <span className={cn("inline-flex rounded-full px-2.5 py-1 text-xs font-semibold ring-1", styles[status] || styles.closed)}>
      {labels[status] || status}
    </span>
  );
}
