# Generated by Django 5.2.15 on 2026-06-19 09:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('businesses', '0005_business_operational_settings'),
        ('clients', '0002_client_archive_reason_client_archived_at_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ClientMergeLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('duplicate_snapshot', models.JSONField(default=dict)),
                ('transferred_counts', models.JSONField(default=dict)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='client_merge_logs', to=settings.AUTH_USER_MODEL)),
                ('business', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='client_merge_logs', to='businesses.business')),
                ('target_client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='merge_logs_as_target', to='clients.client')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['business', 'target_client', 'created_at'], name='clients_cli_busines_23d385_idx'), models.Index(fields=['business', 'created_at'], name='clients_cli_busines_b82296_idx')],
            },
        ),
    ]
