# Generated by Django 5.2.14 on 2026-05-11 10:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('businesses', '0001_initial'),
        ('clients', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AnalyticsEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(choices=[('lead_created', 'Lead created'), ('appointment_created', 'Appointment created'), ('appointment_cancelled', 'Appointment cancelled'), ('appointment_completed', 'Appointment completed'), ('message_received', 'Message received'), ('message_sent', 'Message sent'), ('form_submitted', 'Form submitted'), ('whatsapp_clicked', 'WhatsApp clicked'), ('telegram_clicked', 'Telegram clicked'), ('phone_clicked', 'Phone clicked')], max_length=64)),
                ('source', models.CharField(blank=True, max_length=64)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('business', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='analytics_events', to='businesses.business')),
                ('client', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='analytics_events', to='clients.client')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
