# Generated by Django 5.2.14 on 2026-05-11 16:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('businesses', '0001_initial'),
        ('clients', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=64)),
                ('color', models.CharField(default='#2563eb', max_length=24)),
                ('source', models.CharField(choices=[('manual', 'Manual'), ('ai', 'AI'), ('behavior', 'Behavior'), ('automation', 'Automation')], default='manual', max_length=32)),
                ('business', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tags', to='businesses.business')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='TaggedObject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entity_type', models.CharField(max_length=96)),
                ('entity_id', models.CharField(max_length=64)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('business', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tagged_objects', to='businesses.business')),
                ('tag', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tagged_objects', to='activities.tag')),
            ],
        ),
        migrations.CreateModel(
            name='ActivityEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('crm', 'CRM'), ('message', 'Message'), ('appointment', 'Appointment'), ('task', 'Task'), ('automation', 'Automation'), ('system', 'System')], default='crm', max_length=32)),
                ('event_type', models.CharField(max_length=96)),
                ('source', models.CharField(blank=True, max_length=64)),
                ('entity_type', models.CharField(blank=True, max_length=96)),
                ('entity_id', models.CharField(blank=True, max_length=64)),
                ('text', models.TextField(blank=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='activity_events', to=settings.AUTH_USER_MODEL)),
                ('business', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activity_events', to='businesses.business')),
                ('client', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='activity_events', to='clients.client')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['business', 'created_at'], name='activities__busines_7ff1ee_idx'), models.Index(fields=['business', 'client', 'created_at'], name='activities__busines_95423b_idx'), models.Index(fields=['business', 'category', 'created_at'], name='activities__busines_83bab7_idx'), models.Index(fields=['entity_type', 'entity_id'], name='activities__entity__535f46_idx')],
            },
        ),
        migrations.CreateModel(
            name='Note',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('entity_type', models.CharField(blank=True, max_length=96)),
                ('entity_id', models.CharField(blank=True, max_length=64)),
                ('text', models.TextField()),
                ('author', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='notes', to=settings.AUTH_USER_MODEL)),
                ('business', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notes', to='businesses.business')),
                ('client', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='client_notes', to='clients.client')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['business', 'client', 'created_at'], name='activities__busines_4734cd_idx'), models.Index(fields=['entity_type', 'entity_id'], name='activities__entity__8af2a9_idx')],
            },
        ),
        migrations.AddConstraint(
            model_name='tag',
            constraint=models.UniqueConstraint(fields=('business', 'name'), name='unique_tag_name_per_business'),
        ),
        migrations.AddIndex(
            model_name='taggedobject',
            index=models.Index(fields=['business', 'entity_type', 'entity_id'], name='activities__busines_49e55c_idx'),
        ),
        migrations.AddConstraint(
            model_name='taggedobject',
            constraint=models.UniqueConstraint(fields=('tag', 'entity_type', 'entity_id'), name='unique_tagged_object'),
        ),
    ]
