# Generated by Django 5.2.14 on 2026-05-19 14:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activities', '0001_initial'),
        ('businesses', '0002_rolepreset_alter_businessmember_role_businessrole_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Segment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=96)),
                ('description', models.TextField(blank=True)),
                ('entity_type', models.CharField(choices=[('client', 'Client')], default='client', max_length=32)),
                ('is_active', models.BooleanField(default=True)),
                ('cached_count', models.PositiveIntegerField(default=0)),
                ('last_evaluated_at', models.DateTimeField(blank=True, null=True)),
                ('business', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='segments', to='businesses.business')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='SegmentFilter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('field', models.CharField(choices=[('full_name', 'Client name'), ('phone', 'Phone'), ('email', 'Email'), ('source', 'Source'), ('notes', 'Notes'), ('tag', 'Tag'), ('created_at', 'Created at')], max_length=64)),
                ('operator', models.CharField(choices=[('equals', 'Equals'), ('contains', 'Contains'), ('in', 'In'), ('gte', 'Greater or equal'), ('lte', 'Less or equal'), ('is_empty', 'Is empty'), ('not_empty', 'Not empty')], default='equals', max_length=32)),
                ('value_json', models.JSONField(blank=True, default=dict)),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('business', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='segment_filters', to='businesses.business')),
                ('segment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='filters', to='activities.segment')),
            ],
            options={
                'ordering': ['segment', 'sort_order', 'id'],
            },
        ),
        migrations.AddIndex(
            model_name='segment',
            index=models.Index(fields=['business', 'entity_type', 'is_active'], name='activities__busines_e145ac_idx'),
        ),
        migrations.AddConstraint(
            model_name='segment',
            constraint=models.UniqueConstraint(fields=('business', 'name', 'entity_type'), name='unique_segment_name_per_business_entity'),
        ),
        migrations.AddIndex(
            model_name='segmentfilter',
            index=models.Index(fields=['business', 'segment', 'field'], name='activities__busines_0f1d6d_idx'),
        ),
    ]
