# Generated by Django 5.2.14 on 2026-05-19 14:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('activities', '0002_segment_segmentfilter_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='taggedobject',
            options={'ordering': ['-created_at']},
        ),
    ]
