# Generated by Django 5.2.14 on 2026-06-16 08:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('activities', '0004_taggedobject_indexes'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='taggedobject',
            name='activities_tag_obj_bus_ent_tag_idx',
        ),
    ]
