# Generated by Django 5.2.14 on 2026-05-11 10:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('businesses', '0001_initial'),
        ('clients', '0001_initial'),
        ('scheduling', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('channel', models.CharField(choices=[('telegram', 'Telegram'), ('whatsapp', 'WhatsApp'), ('email', 'Email'), ('sms', 'SMS'), ('system', 'System')], default='system', max_length=32)),
                ('text', models.TextField()),
                ('send_at', models.DateTimeField()),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('sent', 'Sent'), ('failed', 'Failed'), ('cancelled', 'Cancelled')], default='pending', max_length=32)),
                ('appointment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='scheduling.appointment')),
                ('business', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='businesses.business')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='notifications', to='clients.client')),
            ],
            options={
                'ordering': ['send_at'],
            },
        ),
    ]
