# Generated by Django 5.2.14 on 2026-05-19 14:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('businesses', '0002_rolepreset_alter_businessmember_role_businessrole_and_more'),
        ('clients', '0002_client_archive_reason_client_archived_at_and_more'),
        ('notifications', '0001_initial'),
        ('scheduling', '0002_appointment_archive_reason_appointment_archived_at_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='notification',
            options={'ordering': ['read_at', '-send_at']},
        ),
        migrations.AddField(
            model_name='notification',
            name='action_label',
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AddField(
            model_name='notification',
            name='action_url',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='notification',
            name='category',
            field=models.CharField(choices=[('sales', 'Sales'), ('finance', 'Finance'), ('system', 'System'), ('ai_alerts', 'AI alerts'), ('outreach', 'Outreach'), ('tasks', 'Tasks')], default='system', max_length=32),
        ),
        migrations.AddField(
            model_name='notification',
            name='priority',
            field=models.CharField(choices=[('low', 'Low'), ('normal', 'Normal'), ('high', 'High'), ('urgent', 'Urgent')], default='normal', max_length=32),
        ),
        migrations.AddField(
            model_name='notification',
            name='read_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='notification',
            name='client',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='notifications', to='clients.client'),
        ),
        migrations.AddIndex(
            model_name='notification',
            index=models.Index(fields=['business', 'status', 'read_at', 'send_at'], name='notificatio_busines_95dae2_idx'),
        ),
        migrations.AddIndex(
            model_name='notification',
            index=models.Index(fields=['business', 'category', 'priority'], name='notificatio_busines_667677_idx'),
        ),
    ]
