# Generated by Django 5.2.14 on 2026-05-14 14:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('businesses', '0002_rolepreset_alter_businessmember_role_businessrole_and_more'),
        ('conversations', '0002_conversation_archive_reason_conversation_archived_at_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='QuickReplyTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=128)),
                ('text', models.TextField()),
                ('category', models.CharField(blank=True, max_length=64)),
                ('channel', models.CharField(choices=[('all', 'All'), ('telegram', 'Telegram'), ('whatsapp', 'WhatsApp'), ('instagram', 'Instagram'), ('website', 'Website'), ('manual', 'Manual')], default='all', max_length=32)),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('business', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quick_reply_templates', to='businesses.business')),
            ],
            options={
                'ordering': ['sort_order', 'title'],
                'indexes': [models.Index(fields=['business', 'channel', 'is_active', 'sort_order'], name='conversatio_busines_7234df_idx')],
            },
        ),
    ]
